namespace Ossuary.Core.Magic
{
    /// <summary>The Necromancer's grave arts and the Cleric's and Paladin's sacred prayers.</summary>
    public static partial class Spells
    {
        static SpellDef[] Necromancy() { const School N = School.Necromancy; return new[] {
            S("drain-life", "Drain Life", 3, N, 5, Mon, 6, "Steals life: damages the target, heals you by half. Not the dead.").Look(FxKind.Drain, Elem.Necrotic),
            S("raise-skeleton", "Raise Skeleton", 3, N, 6, Self, 0, "A skeleton claws out of the floor to serve you.", 0, 1),
            S("ossify", "Ossify", 3, N, 5, Self, 0, "Bone creeps over your skin: AC +4 for a while. The Ossuary takes a little of you for it.").Look(FxKind.Swirl, Elem.Earth),
            S("reshape-flesh", "Reshape Flesh", 3, N, 8, Self, 0, "Asks the Ossuary for a gift. You get a mutation, and it gets a share of you.").Look(FxKind.Implode, Elem.Blood),
            S("marrow-bolt", "Marrow Bolt", 4, N, 7, Mon, 7, "A spike of grave-cold marrow. Hits hard; the Ossuary takes a little of you each time. Not the dead.").Look(FxKind.Bolt, Elem.Necrotic, 'x'),
            S("fear", "Fear", 4, N, 8, Mon, 6, "The target flees in terror. Mindless things do not fear.").Look(FxKind.Mark, Elem.Shadow, '!'),
            S("finger-of-death", "Finger of Death", 5, N, 15, Mon, 6, "Unmakes the living with a point of the hand.").Look(FxKind.Beam, Elem.Necrotic),
            S("army-of-bones", "Army of Bones", 5, N, 14, Self, 0, "Three skeletons rise to guard you.", 0, 3),

            S("chill-touch", "Chill Touch", 1, N, 2, Mon, 1, "A grave-cold hand. Hurts, and the target hits worse for a while.").Dmg(Necro, 2, 6, 3, 0, "A cold hand grips").Ride(Rider.Weaken, 40, 6).Look(FxKind.Slash, Elem.Necrotic),
            S("bone-shard", "Bone Shard", 1, N, 3, Mon, 7, "A splinter of bone flung with a flick.").Dmg(Phys, 2, 6, 3, 0, "A bone shard hits").Look(FxKind.Bolt, Elem.Earth, '\0'),
            S("enfeeble", "Enfeeble", 2, N, 4, Mon, 7, "A grey ray saps the target: it takes more from every blow for a good while.").Ride(Rider.Weaken, 100, 12).Look(FxKind.Beam, Elem.Necrotic),
            S("wither", "Wither", 2, N, 4, Mon, 6, "Rots a limb. Damages and slows.").Dmg(Necro, 3, 4, 3, 0, "Rot spreads through").Ride(Rider.Slow, 60, 8).Look(FxKind.Bolt, Elem.Necrotic, 'x'),
            S("vampiric-touch", "Vampiric Touch", 2, N, 4, Mon, 1, "A touch that takes it all back: you heal what you deal.").Dmg(Necro, 3, 6, 3, 0, "Your touch drinks from").Drain(100).Look(FxKind.Drain, Elem.Blood),
            S("curse-of-weakness", "Curse of Weakness", 2, N, 4, Area, 6, "A muttered curse on everything around a spot: they take more from every blow.", 1).Ride(Rider.Weaken, 100, 15).Look(FxKind.Cloud, Elem.Shadow),
            S("grave-chill", "Grave Chill", 2, N, 4, Self, 0, "Graveyard cold wraps you: necrotic 50%, cold 30%.").Aura("grave-ward", 60).Look(FxKind.Swirl, Elem.Necrotic),
            S("life-tap", "Life Tap", 2, N, 1, Self, 0, "Burns 8 of your HP into 8 mana.").Spec("life-tap").Look(FxKind.Implode, Elem.Blood),
            S("bone-hound", "Bone Hound", 2, N, 5, Self, 0, "A hound of knit bones runs at your heel.", 0, 1).Call("bone hound", 1, 100),
            S("plague-bolt", "Plague Bolt", 3, N, 6, Mon, 7, "A greasy green bolt. The target sickens for a while.").Dmg(Pois, 2, 6, 3, 0, "Plague eats into").Ride(Rider.Poison, 100, 8).Look(FxKind.Bolt, Elem.Poison, 'o'),
            S("rotting-burst", "Rotting Burst", 3, N, 7, Area, 7, "A bubble of rot bursts around a spot.", 2).Dmg(Necro, 3, 6, 3, 0, "Rot spatters").Look(FxKind.Ball, Elem.Necrotic, 'o'),
            S("hemorrhage", "Hemorrhage", 3, N, 6, Mon, 6, "Opens the target's veins from across the room: it bleeds for a while.").Dmg(Phys, 2, 6, 3, 0, "Blood bursts from").Ride(Rider.Bleed, 100, 6).Look(FxKind.Bolt, Elem.Blood, 'o'),
            S("bone-spear", "Bone Spear", 3, N, 7, Ln, 8, "A lance of bone that pierces every creature in a line.").Dmg(Phys, 3, 6, 3, 0, "A bone spear skewers").Look(FxKind.Beam, Elem.Earth),
            S("dread", "Dread", 3, N, 7, Self, 0, "A wave of dread: every creature within 5 cells may flee.", 5).Ride(Rider.Fear, 70, 10).Look(FxKind.Nova, Elem.Shadow),
            S("unholy-vigor", "Unholy Vigor", 3, N, 6, Self, 0, "Your blows carry grave-cold (+1d4 necrotic) and feed you (15% life steal).").Aura("unholy-vigor", 40).Look(FxKind.Swirl, Elem.Necrotic),
            S("dark-pact", "Dark Pact", 3, N, 4, Self, 0, "Spell power +4 for a good while. The Ossuary takes 6 points of corruption for it.").Aura("dark-pact", 60).Taint(6).Look(FxKind.Swirl, Elem.Blood),
            S("command-undead", "Command Undead", 3, N, 8, Mon, 6, "An undead creature bends its knee to you for a while.").Spec("command-undead").Look(FxKind.Mark, Elem.Necrotic, '♥'),
            S("animate-ghoul", "Animate Ghoul", 3, N, 7, Self, 0, "A ghoul lurches up to serve you. It is always hungry.", 0, 1).Call("ghoul", 1, 120).Taint(1),
            S("bloodlust", "Bloodlust", 3, N, 6, Self, 0, "Red heat behind the eyes: +2 to hit, +3 damage, a little life steal.").Aura("bloodlust", 30).Look(FxKind.Swirl, Elem.Blood),
            S("feign-death", "Feign Death", 3, N, 6, Self, 0, "You go still and cold. Everything nearby loses track of you.").Spec("feign-death").Look(FxKind.Cloud, Elem.Necrotic),
            S("gravebind", "Gravebind", 3, N, 6, Area, 7, "Dead hands grab at the floor-bound: creatures within 2 cells are held.", 2).Dmg(Phys, 1, 6, 4, 0, "Dead hands rake").Ride(Rider.Root, 80, 6).Look(FxKind.Eruption, Elem.Necrotic, '^'),
            S("skull-barrage", "Skull Barrage", 3, N, 7, Self, 0, "Three screaming skulls fly at creatures in view.").Dmg(Necro, 2, 6, 4, 0, "A skull bites").Scatter(3, FxKind.Bolt).Look(FxKind.Custom, Elem.Necrotic, 'o'),
            S("death-aura", "Death Aura", 3, N, 7, Self, 0, "A shroud of cold death: those who strike you take 1d6 necrotic.").Aura("death-aura", 40).Look(FxKind.Swirl, Elem.Necrotic),
            S("contagion", "Contagion", 4, N, 9, Area, 7, "A sickness that sticks. Everything near the spot is poisoned for long.", 2).Dmg(Pois, 2, 6, 3, 0, "Sickness racks").Ride(Rider.Poison, 100, 10).Look(FxKind.Cloud, Elem.Poison),
            S("cloudkill", "Cloudkill", 4, N, 9, Area, 7, "A killing green fog three cells across.", 3).Dmg(Pois, 3, 6, 3, 0, "The fog chokes").Ride(Rider.Poison, 80, 6).Look(FxKind.Cloud, Elem.Poison),
            S("siphon-soul", "Siphon Soul", 4, N, 10, Mon, 6, "Pulls a piece of soul out of the target and into you.").Dmg(Necro, 4, 6, 3, 0, "A piece of soul tears from").Drain(100).Taint(1).Look(FxKind.Drain, Elem.Necrotic),
            S("death-wave", "Death Wave", 4, N, 10, Self, 0, "A ring of death sweeps 3 cells out from you.", 3).Dmg(Necro, 3, 6, 3, 0, "Death washes over").Taint(1).Look(FxKind.Nova, Elem.Necrotic),
            S("banshee-wail", "Banshee Wail", 4, N, 9, Self, 0, "A scream that hurts and sends the living running. 4 cells.", 4).Dmg(Necro, 2, 6, 3, 0, "A wail flays").Ride(Rider.Fear, 70, 10).Look(FxKind.Nova, Elem.Shadow),
            S("raise-wight", "Raise Wight", 4, N, 10, Self, 0, "A wight in rotted mail steps out of the dark and kneels.", 0, 1).Call("wight", 1, 150).Taint(1),
            S("bone-golem", "Bone Golem", 4, N, 11, Self, 0, "A golem of a hundred skeletons, wired together, answers you.", 0, 1).Call("bone golem", 1, 150).Taint(1),
            S("soul-reap", "Soul Reap", 5, N, 15, Self, 0, "Everything living within 5 cells gives up a piece of its soul; you keep a quarter of it.", 5).Dmg(Necro, 5, 6, 3, 0, "Your scythe of dark passes through").Drain(25).Taint(2).Look(FxKind.Nova, Elem.Necrotic),
            S("power-word-kill", "Power Word Kill", 5, N, 18, Mon, 6, "One word. Whatever is badly hurt dies; whatever is not takes a great blow.").Spec("execute").Look(FxKind.Mark, Elem.Necrotic, '☻'),
            S("summon-wraith", "Summon Wraith", 5, N, 14, Self, 0, "A wraith, bound to you for a time, comes through the wall.", 0, 1).Call("wraith thrall", 1, 120).Taint(2),
            S("ritual-of-blood", "Ritual of Blood", 5, N, 8, Self, 0, "Cut yourself for a quarter of your life; take your mana back to the brim.").Spec("blood-ritual").Look(FxKind.Implode, Elem.Blood),
        }; }

        static SpellDef[] Sacred() { const School H = School.Sacred; return new[] {
            S("cure-wounds", "Cure Wounds", 1, H, 3, Self, 0, "Mends your flesh: 2d6 plus Wisdom and level.").Look(FxKind.Rise, Elem.Holy, '+'),
            S("bless", "Bless", 1, H, 3, Self, 0, "A steadier hand: +2 to hit for a long while.").Look(FxKind.Swirl, Elem.Holy),
            S("smite", "Smite", 2, H, 4, Mon, 7, "Radiant wrath. The undead take double.").Look(FxKind.Pillar, Elem.Holy),
            S("cleanse", "Cleanse", 2, H, 3, Self, 0, "Burns away poison, confusion, blindness and visions.").Look(FxKind.Rise, Elem.Water, '·'),
            S("turn-undead", "Turn Undead", 2, H, 5, Self, 0, "Every undead in sight burns and flees.", 5).Look(FxKind.Nova, Elem.Holy),
            S("greater-heal", "Greater Heal", 3, H, 8, Self, 0, "A great mending: 4d8 plus Wisdom and level.").Look(FxKind.Rise, Elem.Nature, '+'),
            S("purify", "Purify", 4, H, 10, Self, 0, "Burns 15 points of the Ossuary's corruption out of you. Mutations stay.").Look(FxKind.Rise, Elem.Holy, '·'),
            S("revive", "Revive", 5, H, 15, Self, 0, "Wards your soul: the next death within 300 turns is undone.").Look(FxKind.Pillar, Elem.Holy),

            S("minor-mending", "Minor Mending", 1, H, 2, Self, 0, "A small mercy: 1d8 plus a little Wisdom.").Heal(1, 8, 0).Look(FxKind.Rise, Elem.Nature, '+'),
            S("sacred-flame", "Sacred Flame", 1, H, 2, Mon, 7, "Light falls on the target like a hand. The undead take double.").Dmg(Holy, 2, 6, 3, 0, "Sacred flame falls on").Look(FxKind.Pillar, Elem.Holy),
            S("holy-light", "Holy Light", 1, H, 2, Self, 0, "A soft light shows the ground about you.", 6).Spec("light").Look(FxKind.Nova, Elem.Holy),
            S("shield-of-faith", "Shield of Faith", 1, H, 3, Self, 0, "Faith rises like a wall: AC +4 for a while.").Aura("faith", 40).Look(FxKind.Swirl, Elem.Holy),
            S("command", "Command", 1, H, 2, Mon, 6, "A single word, in a voice not yours: 'flee'.").Ride(Rider.Fear, 60, 4).Look(FxKind.Mark, Elem.Holy, '!'),
            S("searing-light", "Searing Light", 2, H, 4, Mon, 8, "A needle of white light. The undead take double.").Dmg(Holy, 3, 6, 3, 0, "Searing light burns").Look(FxKind.Beam, Elem.Holy),
            S("divine-favor", "Divine Favor", 2, H, 4, Self, 0, "+3 to hit, +2 damage and a die of holy fire on your blows, for a while.").Aura("favor", 30).Look(FxKind.Swirl, Elem.Holy),
            S("protection-from-evil", "Protection from Evil", 2, H, 4, Self, 0, "A ring of white fire: AC +3 and necrotic resistance 40%.").Aura("prot-evil", 50).Look(FxKind.Swirl, Elem.Holy),
            S("heroism", "Heroism", 2, H, 4, Self, 0, "Courage in the chest: +3 to hit, Str +1.").Aura("heroism", 50).Look(FxKind.Swirl, Elem.Blood),
            S("remedy", "Remedy", 2, H, 3, Self, 0, "Draws poison out of the blood.").Spec("remedy").Look(FxKind.Rise, Elem.Nature, '+'),
            S("second-wind", "Second Wind", 2, H, 3, Self, 0, "Your breath and your legs come back: Vigor to the brim.").Spec("second-wind").Look(FxKind.Rise, Elem.Wind, '\''),
            S("blinding-light", "Blinding Light", 2, H, 4, Cn, 4, "A cone of white light that leaves its victims blind.", 4).Ride(Rider.Blind, 80, 6).Look(FxKind.Cone, Elem.Holy),
            S("spiritual-weapon", "Spiritual Weapon", 2, H, 4, Self, 0, "A hammer of light fights beside you for a time.", 0, 1).Call("spiritual weapon", 1, 30),
            S("regeneration", "Regeneration", 3, H, 6, Self, 0, "Wounds close by themselves: 2 HP a turn for a while.").Aura("regen", 20).Look(FxKind.Rise, Elem.Nature, '+'),
            S("sanctuary", "Sanctuary", 3, H, 7, Self, 0, "A hush: few will lift a hand against you.").Aura("sanctuary", 20).Look(FxKind.Nova, Elem.Holy),
            S("prayer", "Prayer", 3, H, 7, Self, 0, "+2 to hit, +2 damage, AC +2, evasion +1.").Aura("prayer", 50).Look(FxKind.Swirl, Elem.Holy),
            S("fortitude", "Fortitude", 3, H, 6, Self, 0, "Con +3 and +15 HP for a long while.").Aura("fortitude", 60).Look(FxKind.Swirl, Elem.Blood),
            S("remove-curse", "Remove Curse", 3, H, 6, Self, 0, "Lifts the curse off everything you carry.").Spec("uncurse").Look(FxKind.Rise, Elem.Holy, '·'),
            S("hammer-of-wrath", "Hammer of Wrath", 3, H, 6, Mon, 6, "A hammer of light. May stun.").Dmg(Holy, 4, 6, 3, 0, "A hammer of light smashes").Ride(Rider.Stun, 40, 2).Look(FxKind.Bolt, Elem.Holy, '†'),
            S("holy-lance", "Holy Lance", 3, H, 7, Ln, 8, "A lance of light that pierces everything in a line.").Dmg(Holy, 3, 8, 3, 0, "A lance of light pierces").Look(FxKind.Beam, Elem.Holy),
            S("consecrate", "Consecrate", 3, H, 7, Area, 7, "Hallows a patch of floor: the light burns whoever stands in it.", 2).Dmg(Holy, 2, 6, 3, 0, "Hallowed light burns").Look(FxKind.Eruption, Elem.Holy, '+'),
            S("hold-person", "Hold Person", 3, H, 6, Mon, 6, "A living target stands rigid for a few turns.").Ride(Rider.Stun, 70, 4).Look(FxKind.Mark, Elem.Holy, '='),
            S("holy-aura", "Holy Aura", 4, H, 9, Self, 0, "A blazing halo: AC +3, necrotic resistance 40%, and those who strike you burn.").Aura("holy-aura", 40).Look(FxKind.Swirl, Elem.Holy),
            S("flame-strike", "Flame Strike", 4, H, 10, Area, 8, "A column of fire from the sky, 3 cells wide.", 1).Dmg(Fire, 5, 6, 3, 0, "A column of fire falls on").Look(FxKind.Pillar, Elem.Fire),
            S("radiant-nova", "Radiant Nova", 4, H, 10, Self, 0, "A ring of light bursts 3 cells out from you.", 3).Dmg(Holy, 3, 6, 3, 0, "Radiance washes over").Look(FxKind.Nova, Elem.Holy),
            S("exorcise", "Exorcise", 4, H, 10, Self, 0, "Burns and routs everything within 5 cells. The undead take double.", 5).Dmg(Holy, 3, 6, 3, 0, "Holy fire scours").Ride(Rider.Fear, 80, 10).Look(FxKind.Nova, Elem.Holy),
            S("sunbeam", "Sunbeam", 4, H, 9, Ln, 8, "A lance of sunlight along a line; what it does not kill, it blinds.").Dmg(Holy, 4, 6, 3, 0, "Sunlight burns").Ride(Rider.Blind, 60, 6).Look(FxKind.Beam, Elem.Holy),
            S("divine-might", "Divine Might", 4, H, 9, Self, 0, "Str +4 and +2 damage for a while.").Aura("divine-might", 40).Look(FxKind.Swirl, Elem.Holy),
            S("spirit-guardians", "Spirit Guardians", 4, H, 10, Self, 0, "Pale spirits whirl about you, hurting and slowing everything within 2 cells.", 2).Dmg(Holy, 2, 6, 3, 0, "Spirits tear at").Ride(Rider.Slow, 70, 6).Aura("faith", 20).Look(FxKind.Nova, Elem.Holy),
            S("restoration", "Restoration", 4, H, 10, Self, 0, "A deep mending: 3d8 plus Wisdom, and every ill state on you ends.").Spec("restoration").Look(FxKind.Rise, Elem.Holy, '+'),
            S("mass-cure", "Mass Cure", 4, H, 11, Self, 0, "Healing light on you and every ally within 5 cells.", 5).Spec("mass-cure").Look(FxKind.Rise, Elem.Holy, '+'),
            S("judgement", "Judgement", 5, H, 16, Area, 8, "A pillar of white fire falls: everything within 3 cells is judged.", 3).Dmg(Holy, 6, 6, 2, 0, "Judgement falls on").Look(FxKind.Pillar, Elem.Holy),
            S("guardian-angel", "Guardian Angel", 5, H, 15, Self, 0, "A winged guardian descends to fight for you.", 0, 1).Call("guardian angel", 1, 60),
            S("angelic-blessing", "Angelic Blessing", 5, H, 14, Self, 0, "For a long while you are a little more than you are.").Aura("angelic", 100).Look(FxKind.Pillar, Elem.Holy),
            S("divine-intervention", "Divine Intervention", 5, H, 16, Self, 0, "Heaven takes a hand: full health, every ill ended, and a hush around you.").Spec("full-heal").Look(FxKind.Pillar, Elem.Holy),
        }; }
    }
}
