namespace Ossuary.Core.Magic
{
    /// <summary>The Ranger's and druid's nature magic, and the Rogue's shadow tricks.</summary>
    public static partial class Spells
    {
        static SpellDef[] Nature() { const School R = School.Nature; return new[] {
            S("thorn-dart", "Thorn Dart", 1, R, 2, Mon, 7, "A poisoned thorn flung hard.").Dmg(Phys, 2, 4, 3, 0, "A thorn pricks").Ride(Rider.Poison, 40, 6).Look(FxKind.Bolt, Elem.Nature, '\0'),
            S("insect-swarm", "Insect Swarm", 1, R, 3, Area, 6, "A cloud of biting flies. Stings, and sets creatures swatting at the air.", 1).Dmg(Pois, 1, 6, 4, 0, "Flies sting").Ride(Rider.Confuse, 40, 6).Look(FxKind.Cloud, Elem.Nature),
            S("barkskin", "Barkskin", 1, R, 3, Self, 0, "Your skin roughens to bark: AC +4 for a long while.").Aura("barkskin", 100).Look(FxKind.Swirl, Elem.Nature),
            S("hunters-mark", "Hunter's Mark", 1, R, 2, Mon, 8, "Marks a quarry: it takes more from every blow for a long while.").Ride(Rider.Weaken, 100, 25).Look(FxKind.Mark, Elem.Blood, '◎'),
            S("herbal-poultice", "Herbal Poultice", 1, R, 2, Self, 0, "Crushed leaves on a wound: 1d8.").Heal(1, 8, 0).Look(FxKind.Rise, Elem.Nature, '+'),
            S("antidote", "Antidote", 1, R, 2, Self, 0, "A bitter root that ends poison.").Spec("antidote").Look(FxKind.Rise, Elem.Nature, '+'),
            S("shillelagh", "Shillelagh", 1, R, 2, Self, 0, "Your weapon thrums like oak: +2 to hit, +3 damage.").Aura("shillelagh", 60).Look(FxKind.Swirl, Elem.Nature),
            S("wild-growth", "Wild Growth", 1, R, 2, Area, 6, "Grass springs up around a spot. Dry brush burns well.", 2).Surf(SurfaceKind.Grass).Look(FxKind.Eruption, Elem.Nature, '"'),
            S("entangle", "Entangle", 2, R, 4, Area, 7, "Roots and vines clutch at everything within 2 cells.", 2).Ride(Rider.Root, 80, 6).Look(FxKind.Eruption, Elem.Nature, '&'),
            S("spike-growth", "Spike Growth", 2, R, 4, Area, 7, "Thorny growth tears at whatever crosses it and slows it.", 2).Dmg(Phys, 2, 4, 3, 0, "Thorns rake").Ride(Rider.Slow, 80, 6).Look(FxKind.Eruption, Elem.Nature, '^'),
            S("thorns", "Thorns", 2, R, 4, Self, 0, "Thorns push through your skin: those who hit you take 1d6.").Aura("thorns", 60).Look(FxKind.Swirl, Elem.Nature),
            S("rejuvenate", "Rejuvenate", 2, R, 4, Self, 0, "Mends 2d6 now, and a little each turn after.").Heal(2, 6, 0).Aura("regen", 10).Look(FxKind.Rise, Elem.Nature, '+'),
            S("goodberries", "Goodberries", 2, R, 3, Self, 0, "A handful of berries: a little healing and a little food.").Spec("goodberries").Look(FxKind.Rise, Elem.Blood, '*'),
            S("eagle-eye", "Eagle Eye", 2, R, 3, Self, 0, "+3 to hit for a while.").Aura("eagle-eye", 60).Look(FxKind.Swirl, Elem.Wind),
            S("camouflage", "Camouflage", 2, R, 4, Self, 0, "You take the colours of the stone: much harder to notice.").Aura("camouflage", 80).Look(FxKind.Swirl, Elem.Earth),
            S("cheetah-sprint", "Cheetah Sprint", 2, R, 4, Self, 0, "A short burst of speed.").Aura("haste", 12).Look(FxKind.Swirl, Elem.Wind),
            S("flame-blade", "Flame Blade", 2, R, 4, Self, 0, "A skin of fire on your weapon: +1d6 fire.").Aura("flame-blade", 40).Look(FxKind.Swirl, Elem.Fire),
            S("speak-with-animals", "Speak with Animals", 2, R, 4, Mon, 6, "A beast listens, and follows you for a while.").Spec("charm-beast").Look(FxKind.Mark, Elem.Nature, '♥'),
            S("calm-beasts", "Calm Beasts", 2, R, 3, Self, 0, "Every beast within 4 cells lies down and sleeps.", 4).Spec("calm-beasts").Look(FxKind.Nova, Elem.Nature),
            S("hoarfrost", "Hoarfrost", 2, R, 4, Area, 7, "A rime of killing frost on a patch of floor.", 2).Dmg(Cold, 2, 6, 3, 0, "Hoarfrost bites").Ride(Rider.Slow, 60, 6).Look(FxKind.Rain, Elem.Cold, '\''),
            S("dust-devil", "Dust Devil", 2, R, 4, Area, 6, "A little whirlwind that batters, blinds and shoves.", 1).Dmg(Phys, 1, 6, 4, 0, "A dust devil lashes").Ride(Rider.Confuse, 60, 6).Shove(1).Look(FxKind.Cloud, Elem.Earth),
            S("lightning-lash", "Lightning Lash", 2, R, 4, Mon, 7, "A whip of lightning from the sky.").Dmg(Elec, 3, 4, 3, 0, "A lash of lightning strikes").Look(FxKind.Zap, Elem.Lightning),
            S("fire-seeds", "Fire Seeds", 2, R, 5, Area, 6, "Seeds that burst into flame where they land.", 1).Dmg(Fire, 3, 6, 3, 0, "A fire seed bursts on").Look(FxKind.Ball, Elem.Fire, 'o'),
            S("poison-spray", "Poison Spray", 2, R, 4, Cn, 3, "A gout of venom three cells long.", 3).Dmg(Pois, 2, 6, 3, 0, "Venom sprays").Ride(Rider.Poison, 70, 6).Look(FxKind.Cone, Elem.Poison),
            S("moonfire", "Moonfire", 2, R, 4, Mon, 8, "Cold white fire from above. The undead take double.").Dmg(Holy, 3, 6, 3, 0, "Moonfire falls on").Look(FxKind.Pillar, Elem.Water),
            S("summon-hawk", "Summon Hawk", 2, R, 4, Self, 0, "A spirit hawk stoops at your enemies.", 0, 1).Call("spirit hawk", 1, 80),
            S("wild-leap", "Wild Leap", 2, R, 3, Cell, 5, "A bound that takes you five cells.").Spec("blink").Look(FxKind.Teleport, Elem.Nature),
            S("bears-endurance", "Bear's Endurance", 3, R, 5, Self, 0, "Con +4 and +10 HP for a long while.").Aura("bears-endurance", 60).Look(FxKind.Swirl, Elem.Earth),
            S("gale", "Gale", 3, R, 6, Cn, 5, "A howling wind that batters and throws creatures back three cells.", 5).Dmg(Phys, 2, 6, 3, 0, "The gale hammers").Shove(3).Look(FxKind.Wave, Elem.Wind),
            S("sleet-storm", "Sleet Storm", 3, R, 6, Area, 8, "Sleet in a wide patch: it hurts, slows, and ices the floor.", 3).Dmg(Cold, 2, 6, 3, 0, "Sleet lashes").Ride(Rider.Slow, 70, 6).Surf(SurfaceKind.Ice, 30).Look(FxKind.Rain, Elem.Water, '|'),
            S("stone-spikes", "Stone Spikes", 3, R, 6, Cn, 4, "Spikes of stone thrust out in a cone four cells long.", 4).Dmg(Phys, 3, 6, 3, 0, "Stone spikes impale").Ride(Rider.Slow, 60, 6).Look(FxKind.Cone, Elem.Earth),
            S("venom-bolt", "Venom Bolt", 3, R, 6, Mon, 7, "A bolt of concentrated venom. The poison lingers.").Dmg(Pois, 4, 6, 3, 0, "Venom eats").Ride(Rider.Poison, 100, 8).Look(FxKind.Bolt, Elem.Poison, 'o'),
            S("spore-cloud", "Spore Cloud", 3, R, 6, Area, 7, "A cloud of spores: stinging, and the mind goes with it.", 2).Dmg(Pois, 1, 6, 4, 0, "Spores burn").Ride(Rider.Confuse, 60, 8).Look(FxKind.Cloud, Elem.Nature),
            S("choking-vines", "Choking Vines", 3, R, 7, Mon, 6, "A single creature caught fast and squeezed.").Dmg(Phys, 3, 6, 3, 0, "Vines crush").Ride(Rider.Root, 100, 5).Look(FxKind.Eruption, Elem.Nature, '&'),
            S("tremor", "Tremor", 3, R, 7, Self, 0, "The ground shudders 3 cells around you: hurts, and may stun.", 3).Dmg(Phys, 3, 6, 3, 0, "The ground shudders under").Ride(Rider.Stun, 40, 2).Look(FxKind.Eruption, Elem.Earth, '^'),
            S("commune", "Commune with Nature", 3, R, 5, Self, 0, "The land tells you what is near: the map within 14 cells, and every trap in it.", 8).Spec("commune").Look(FxKind.Nova, Elem.Nature),
            S("spirit-wolves", "Spirit Wolves", 3, R, 8, Self, 0, "Two wolves of pale light hunt for you.", 0, 2).Call("spirit wolf", 2, 120),
            S("spirit-boar", "Spirit Boar", 3, R, 7, Self, 0, "A spirit boar charges your enemies.", 0, 1).Call("spirit boar", 1, 100),
            S("giant-spider", "Spirit Spider", 3, R, 7, Self, 0, "A spirit spider, all legs and venom, serves you.", 0, 1).Call("spirit spider", 1, 100),
            S("wolf-form", "Wolf Form", 4, R, 9, Self, 0, "You take a wolf's shape: Str +3, Dex +3, AC +2, evasion +2.").Aura("wolf-form", 40).Look(FxKind.Swirl, Elem.Shadow),
            S("bear-form", "Bear Form", 4, R, 10, Self, 0, "You take a bear's shape: Str +5, Con +4, +20 HP, AC +3.").Aura("bear-form", 40).Look(FxKind.Swirl, Elem.Earth),
            S("eagle-form", "Eagle Form", 4, R, 9, Self, 0, "You take an eagle's shape: Dex +4, evasion +4.").Aura("eagle-form", 40).Look(FxKind.Swirl, Elem.Wind),
            S("tornado", "Tornado", 4, R, 9, Area, 7, "A howling funnel: crushes, shoves and blinds.", 2).Dmg(Phys, 4, 6, 3, 0, "The tornado flings").Ride(Rider.Confuse, 60, 6).Shove(2).Look(FxKind.Cloud, Elem.Wind),
            S("rockslide", "Rockslide", 4, R, 9, Area, 8, "A rain of boulders from above.", 2).Dmg(Phys, 4, 6, 3, 0, "Boulders crush").Ride(Rider.Stun, 40, 2).Look(FxKind.Rain, Elem.Earth, '#'),
            S("briar-wall", "Briar Wall", 4, R, 9, Area, 7, "A wall of iron-hard thorns springs up and holds what it catches.", 2).Dmg(Phys, 3, 6, 3, 0, "Briars tear").Ride(Rider.Root, 90, 6).Look(FxKind.Eruption, Elem.Nature, '^'),
            S("healing-rain", "Healing Rain", 4, R, 10, Self, 0, "A warm rain that heals you and every ally within 5 cells.", 5).Spec("mass-cure").Look(FxKind.Rain, Elem.Water, '\''),
            S("summon-bear", "Summon Bear", 4, R, 10, Self, 0, "A spirit bear lumbers up beside you.", 0, 1).Call("spirit bear", 1, 120),
            S("lightning-storm", "Lightning Storm", 5, R, 15, Self, 0, "Five bolts on five creatures in view.").Dmg(Elec, 4, 6, 4, 0, "Lightning smites").Scatter(5, FxKind.Pillar).Look(FxKind.Custom, Elem.Lightning),
            S("starfall", "Starfall", 5, R, 16, Self, 0, "Four stars fall on four creatures in view.").Dmg(Phys, 5, 6, 4, 0, "A falling star crushes").Scatter(4, FxKind.Meteor).Look(FxKind.Custom, Elem.Arcane),
            S("treant", "Treant", 5, R, 15, Self, 0, "An old tree walks.", 0, 1).Call("treant", 1, 200),
        }; }

        static SpellDef[] Shadow() { const School D = School.Shadow; return new[] {
            S("shadow-bolt", "Shadow Bolt", 1, D, 2, Mon, 7, "A bolt of cold dark. Not the dead.").Dmg(Necro, 2, 6, 3, 0, "A shadow bolt rips").Look(FxKind.Bolt, Elem.Shadow, '*'),
            S("throwing-knives", "Throwing Knives", 1, D, 2, Mon, 7, "A flick of the wrist: three knives you did not have a moment ago.").Dmg(Phys, 2, 4, 3, 0, "Knives bite").Look(FxKind.Bolt, Elem.Wind, '\0'),
            S("poison-dart", "Poison Dart", 1, D, 2, Mon, 7, "A tiny dart, a lot of poison.").Dmg(Pois, 1, 6, 4, 0, "A dart pricks").Ride(Rider.Poison, 100, 6).Look(FxKind.Bolt, Elem.Poison, '\0'),
            S("blinding-powder", "Blinding Powder", 1, D, 2, Cn, 2, "A fistful of pepper and ash in the face of everything in front of you.", 2).Ride(Rider.Blind, 80, 5).Look(FxKind.Cone, Elem.Earth),
            S("venom-blade", "Venom Blade", 1, D, 3, Self, 0, "Your weapon beads with venom: +1d6 poison.").Aura("venom-blade", 30).Look(FxKind.Swirl, Elem.Poison),
            S("hex", "Hex", 1, D, 2, Mon, 6, "A muttered hex: the target's feet drag.").Ride(Rider.Slow, 70, 8).Look(FxKind.Mark, Elem.Shadow, 'x'),
            S("skeleton-key", "Skeleton Key", 1, D, 2, Self, 0, "Unlocks every locked door within 5 cells.", 5).Spec("knock").Look(FxKind.Swirl, Elem.Wind),
            S("cloak-of-shadows", "Cloak of Shadows", 2, D, 4, Self, 0, "Shadow gathers about you: much harder to notice, evasion +2.").Aura("shadow-cloak", 50).Look(FxKind.Swirl, Elem.Shadow),
            S("shadow-step", "Shadow Step", 2, D, 4, Cell, 6, "From one shadow to another, six cells away.").Spec("blink").Look(FxKind.Teleport, Elem.Shadow),
            S("smoke-bomb", "Smoke Bomb", 2, D, 4, Self, 0, "A burst of black smoke: foes within 2 cells go blind, and you slip out of sight.", 2).Ride(Rider.Blind, 70, 5).Aura("shadow-cloak", 6).Look(FxKind.Cloud, Elem.Shadow),
            S("mark-for-death", "Mark for Death", 2, D, 3, Mon, 8, "A quarry marked: it takes more from every blow for a long while.").Ride(Rider.Weaken, 100, 30).Look(FxKind.Mark, Elem.Blood, '◎'),
            S("caltrops", "Caltrops", 2, D, 3, Area, 5, "A scatter of iron spikes: hurts and slows.", 1).Dmg(Phys, 1, 6, 4, 0, "Caltrops pierce").Ride(Rider.Slow, 80, 8).Look(FxKind.Eruption, Elem.Earth, '^'),
            S("cripple", "Cripple", 2, D, 4, Mon, 1, "A cut to the hamstring: it hobbles after you.").Dmg(Phys, 2, 6, 3, 0, "A cut hobbles").Ride(Rider.Slow, 100, 12).Look(FxKind.Slash, Elem.Blood),
            S("mind-spike", "Mind Spike", 2, D, 4, Mon, 7, "A needle of thought driven into the target's head.").Dmg(Phys, 3, 4, 3, 0, "A spike of thought pierces").Ride(Rider.Confuse, 40, 6).Look(FxKind.Bolt, Elem.Mind, '*'),
            S("venom-spit", "Venom Spit", 2, D, 4, Cn, 3, "A spray of venom from between your teeth.", 3).Dmg(Pois, 1, 6, 4, 0, "Venom spatters").Ride(Rider.Poison, 80, 6).Look(FxKind.Cone, Elem.Poison),
            S("light-fingers", "Light Fingers", 2, D, 3, Mon, 1, "Lifts a few coins off whatever you touch.").Spec("pickpocket").Look(FxKind.Slash, Elem.Wind),
            S("disarm-traps", "Disarm Traps", 2, D, 3, Self, 0, "Disarms every trap within 3 cells.", 3).Spec("disarm").Look(FxKind.Nova, Elem.Earth),
            S("shade-strike", "Shade Strike", 2, D, 4, Cn, 3, "A cone of living shadow that bites and frightens.", 3).Dmg(Necro, 2, 6, 3, 0, "Shadows bite").Ride(Rider.Fear, 40, 6).Look(FxKind.Cone, Elem.Shadow),
            S("gloom", "Gloom", 2, D, 3, Area, 6, "A patch of unnatural dark: creatures in it fight blind and take more.", 2).Ride(Rider.Weaken, 100, 12).Look(FxKind.Cloud, Elem.Shadow),
            S("shadow-blade", "Shadow Blade", 3, D, 5, Self, 0, "Your weapon drinks the light: +1d6 necrotic, +2 to hit.").Aura("shadow-blade", 30).Look(FxKind.Swirl, Elem.Shadow),
            S("vampiric-edge", "Vampiric Edge", 3, D, 5, Self, 0, "Your weapon thirsts: a quarter of what you deal comes back.").Aura("vampiric-edge", 30).Look(FxKind.Swirl, Elem.Blood),
            S("shadow-clone", "Shadow Clone", 3, D, 6, Self, 0, "Your shadow steps off the floor and fights.", 0, 1).Call("shadow double", 1, 30),
            S("umbral-grasp", "Umbral Grasp", 3, D, 6, Mon, 6, "Hands of shadow rise and hold the target.").Dmg(Necro, 2, 6, 3, 0, "Dark hands crush").Ride(Rider.Root, 90, 3).Look(FxKind.Eruption, Elem.Shadow, '~'),
            S("veil-of-darkness", "Veil of Darkness", 3, D, 6, Self, 0, "The dark thickens: everything nearby loses track of you.", 4).Spec("darkness").Look(FxKind.Cloud, Elem.Shadow),
            S("knife-flurry", "Knife Flurry", 3, D, 7, Self, 0, "Three knives each find a creature in view.").Dmg(Phys, 2, 6, 4, 0, "A knife bites").Scatter(3, FxKind.Bolt).Look(FxKind.Custom, Elem.Wind, '\0'),
            S("fade", "Fade", 3, D, 6, Self, 0, "You are hard to look at and harder to hit: evasion +5, hard to notice.").Aura("fade", 20).Look(FxKind.Swirl, Elem.Shadow),
            S("dread-gaze", "Dread Gaze", 3, D, 6, Mon, 6, "A look that shows the target its own death.").Ride(Rider.Fear, 80, 10).Look(FxKind.Mark, Elem.Shadow, '☻'),
            S("umbral-shroud", "Umbral Shroud", 3, D, 6, Self, 0, "A shroud of dark folds around you: AC +2, necrotic 30%, cold 20%.").Aura("umbral-shroud", 40).Look(FxKind.Swirl, Elem.Shadow),
            S("night-whip", "Night Whip", 3, D, 6, Ln, 6, "A whip of darkness that lashes everything along a line.").Dmg(Necro, 3, 6, 3, 0, "A whip of night lashes").Look(FxKind.Beam, Elem.Shadow),
            S("assassinate", "Assassinate", 4, D, 8, Mon, 1, "A killing blow: double damage on anything asleep or unaware.").Spec("assassinate").Look(FxKind.Slash, Elem.Blood),
            S("black-tentacles", "Black Tentacles", 4, D, 9, Area, 7, "Tentacles of dark crush and hold everything within 2 cells.", 2).Dmg(Necro, 3, 6, 3, 0, "Black tentacles crush").Ride(Rider.Root, 80, 5).Look(FxKind.Eruption, Elem.Shadow, '~'),
            S("void-rift", "Void Rift", 4, D, 10, Area, 7, "A small hole in the world, pulling everything near it in.", 2).Dmg(Necro, 3, 6, 3, 0, "The rift tears at").Shove(-2).Look(FxKind.Implode, Elem.Shadow),
            S("vanish", "Vanish", 4, D, 9, Self, 0, "Smoke, a sleight, and you are not here: invisible, and everyone has lost you.", 3).Spec("vanish").Look(FxKind.Cloud, Elem.Shadow),
            S("coup-de-grace", "Coup de Grace", 4, D, 8, Mon, 1, "Finishes anything badly hurt; a sound blow on the rest.").Spec("coup-de-grace").Look(FxKind.Slash, Elem.Blood),
            S("soul-dagger", "Soul Dagger", 4, D, 9, Mon, 7, "A dagger of stolen life; half of what it takes comes back to you.").Dmg(Necro, 4, 6, 3, 0, "A soul dagger pierces").Drain(50).Look(FxKind.Bolt, Elem.Blood, '\0'),
            S("quicken-shadow", "Quicken Shadow", 4, D, 9, Self, 0, "A short burst of speed.").Aura("haste", 10).Look(FxKind.Swirl, Elem.Shadow),
            S("eclipse", "Eclipse", 5, D, 14, Self, 0, "The light dies for 5 cells: everything in it is hurt and blind.", 5).Dmg(Necro, 4, 6, 3, 0, "Darkness crushes").Ride(Rider.Blind, 80, 6).Look(FxKind.Nova, Elem.Shadow),
            S("shadow-walk", "Shadow Walk", 5, D, 12, Self, 0, "Step into the dark and out elsewhere on the level, unseen.").Spec("shadow-walk").Look(FxKind.Custom, Elem.Shadow),
            S("dominate", "Dominate", 5, D, 16, Mon, 6, "A living creature becomes yours for a long while.").Ride(Rider.Charm, 90, 80).Look(FxKind.Mark, Elem.Mind, '♥'),
        }; }
    }
}
