using System.Collections.Generic;

namespace Ossuary.Core
{
    /// <summary>Portuguese names and descriptions of every spell, keyed by spell id (see docs/idiomas.md). The test suite checks that none is missing.</summary>
    public static partial class Loc
    {
        public static readonly Dictionary<string, (string Name, string Blurb)> SpellPt = new Dictionary<string, (string, string)>
        {
            // ---- Evocação
            ["magic-missile"] = ("Míssil Mágico", "Raios de força que não erram. Os dados crescem com o nível."),
            ["shocking-grasp"] = ("Toque Chocante", "Raio pelo seu toque. Só adjacente; bate forte."),
            ["frost-ray"] = ("Raio de Gelo", "Um feixe de frio. Dano alto, exige linha livre."),
            ["fireball"] = ("Bola de Fogo", "Explode onde você mira e queima tudo a 2 casas."),
            ["lightning-bolt"] = ("Relâmpago", "Um raio que atravessa toda criatura na linha."),
            ["chain-lightning"] = ("Raio em Cadeia", "Atinge o alvo e salta para até três outros por perto."),
            ["wall-of-fire"] = ("Muralha de Fogo", "Uma cruz em chamas no chão. Se espalha em mato e óleo; quem está nela pega fogo."),
            ["meteor"] = ("Meteoro", "Uma rocha em chamas vinda do nada. Devasta 3 casas ao redor."),
            ["ice-lance"] = ("Lança de Gelo", "Uma lança de gelo. Resfria o alvo e congela a água em que ele pisa."),
            ["steam-burst"] = ("Jato de Vapor", "Ferve a água em vapor: dano alto em molhados a 2 casas, e a água some. No seco, só chia."),
            ["ember-dart"] = ("Dardo de Brasa", "Uma centelha de fogo. De vez em quando incendeia o alvo."),
            ["frostbite"] = ("Geladura", "Uma mordida de frio que atrasa o alvo."),
            ["spark"] = ("Faísca", "Um estalo de raio. Rápido e barato."),
            ["burning-hands"] = ("Mãos Flamejantes", "Um leque de chamas dos seus dedos, três casas de comprimento."),
            ["acid-splash"] = ("Respingo Ácido", "Um bocado de ácido. Corrói a armadura: o alvo sofre mais de tudo por um tempo."),
            ["thunderclap"] = ("Trovão", "Uma palma ensurdecedora: fere tudo a 2 casas e pode atordoar."),
            ["scorching-ray"] = ("Raio Escaldante", "Uma agulha de fogo branco. Incendeia o alvo."),
            ["stone-shard"] = ("Estilhaço de Pedra", "Uma pedra pontuda arremessada com força."),
            ["gust-of-wind"] = ("Rajada de Vento", "Um golpe de ar que fere e empurra as coisas duas casas para trás."),
            ["forked-lightning"] = ("Raio Bifurcado", "Um raio que se divide e atinge mais uma criatura por perto."),
            ["poison-cloud"] = ("Nuvem Venenosa", "Uma nuvem verde e podre. Tudo nela fica envenenado por alguns turnos."),
            ["lava-bolt"] = ("Dardo de Lava", "Um bocado de rocha derretida. Queima e deixa chamas no chão onde cai."),
            ["cone-of-cold"] = ("Cone de Gelo", "Um cone de geada mortal, cinco casas de comprimento. Atrasa quem sobrevive."),
            ["ice-storm"] = ("Tempestade de Gelo", "Granizo do tamanho de punhos, numa área larga."),
            ["call-lightning"] = ("Chamar Raios", "Três raios caem do nada sobre criaturas à vista."),
            ["prismatic-spray"] = ("Leque Prismático", "Um leque de luz colorida: fere e atordoa."),
            ["disintegrate"] = ("Desintegrar", "Um raio verde que desfaz o que toca."),
            ["sunburst"] = ("Explosão Solar", "Um sol cai: varre tudo a 3 casas e cega o que não matar."),
            ["earthquake"] = ("Terremoto", "O chão sacode por 4 casas ao seu redor. Fere e atordoa tudo que está nele."),

            // ---- Conjuração
            ["familiar"] = ("Familiar", "Chama uma fera pequena para lutar por você por um tempo."),
            ["summon-beast"] = ("Invocar Fera", "Chama uma fera mais forte conforme você sobe de nível."),
            ["create-water"] = ("Criar Água", "Inunda o chão ao redor de um ponto. Molhados queimam menos e conduzem raios; o gelo congela tudo."),
            ["create-oil"] = ("Criar Óleo", "Unta o chão com óleo. Queima por muito tempo e faz os incautos escorregarem. Cuidado com tochas."),
            ["blink"] = ("Piscar", "Atravessa o espaço até um ponto que você vê."),
            ["teleport"] = ("Teletransporte", "Joga você num lugar aleatório deste nível."),
            ["spectral-blade"] = ("Lâmina Espectral", "Uma espada de luz fria luta ao seu lado por um tempo."),
            ["phase-step"] = ("Passo de Fase", "Um salto curto através das paredes do mundo."),
            ["web"] = ("Teia", "Fios grudentos numa área pequena. O que toca fica preso por alguns turnos."),
            ["fog-cloud"] = ("Nuvem de Névoa", "Uma névoa densa: inimigos a 2 casas tateiam às cegas e você fica mais difícil de acertar."),
            ["summon-swarm"] = ("Invocar Enxame", "Uma nuvem de morcegos atende ao seu chamado."),
            ["mirror-image"] = ("Imagem Espelhada", "Dois duplos seus tremeluzem ao lado, atraindo golpes feitos para você."),
            ["swap-places"] = ("Trocar de Lugar", "Você e o alvo trocam de posição num piscar."),
            ["frozen-ground"] = ("Chão Congelado", "O gelo se espalha pelo chão e quem pisa nele fica lento."),
            ["banish"] = ("Banir", "Joga o alvo para longe, em outra parte do nível."),
            ["dimension-door"] = ("Porta Dimensional", "Um passo longo através das paredes do mundo."),
            ["summon-fire-elemental"] = ("Invocar Elemental de Fogo", "Um elemental de fogo rasga o nada para te servir."),
            ["summon-water-elemental"] = ("Invocar Elemental de Água", "Um elemental de água se ergue, pingando, para te servir."),
            ["summon-earth-elemental"] = ("Invocar Elemental de Terra", "Um elemental de terra se arranca do chão para te servir."),
            ["summon-air-elemental"] = ("Invocar Elemental de Ar", "Um elemental de ar rodopiante atende você."),

            // ---- Alteração
            ["ward"] = ("Proteção", "Um escudo cintilante: CA +3 por um tempo."),
            ["haste"] = ("Aceleração", "Você age duas vezes mais que o resto, por pouco tempo."),
            ["slow"] = ("Lentidão", "Reduz à metade a velocidade de uma criatura. As fortes resistem."),
            ["clairvoyance"] = ("Clarividência", "O nível inteiro se abre na sua mente."),
            ["stone-skin"] = ("Pele de Pedra", "Sua pele endurece: CA +6 por bastante tempo."),
            ["light"] = ("Luz", "Um clarão mostra o chão ao redor."),
            ["detect-traps"] = ("Achar Armadilhas", "Mostra toda armadilha a 10 casas."),
            ["knock"] = ("Arrombar", "Destranca e abre toda porta trancada a 3 casas."),
            ["mage-armor"] = ("Armadura Arcana", "Placas de força invisível: CA +4 por bastante tempo."),
            ["arcane-shield"] = ("Escudo", "Um disco de força à sua frente: CA +6, mas só por poucos turnos."),
            ["detect-monsters"] = ("Sentir a Vida", "Por um tempo você sente toda coisa viva a 12 casas, através das paredes."),
            ["identify"] = ("Identificar", "Tudo que você carrega e veste mostra o que é."),
            ["bulls-strength"] = ("Força do Touro", "Força +3 por bastante tempo."),
            ["cats-grace"] = ("Graça do Gato", "Destreza +3 e um pouco de evasão, por bastante tempo."),
            ["foxs-cunning"] = ("Astúcia da Raposa", "Inteligência +3 por bastante tempo. Sua reserva de mana cresce junto."),
            ["owls-wisdom"] = ("Sabedoria da Coruja", "Sabedoria +3 por bastante tempo. Sua mana cresce junto, se você conjura por Sabedoria."),
            ["endure-elements"] = ("Suportar Elementos", "Fogo e frio 30%, raio 20%, por bastante tempo."),
            ["fire-ward"] = ("Proteção contra Fogo", "Resistência a fogo 60% por um tempo."),
            ["frost-ward"] = ("Proteção contra Gelo", "Resistência a frio 60% por um tempo."),
            ["storm-ward"] = ("Proteção contra Raios", "Resistência a raios 60% por um tempo."),
            ["blur"] = ("Borrão", "Seu contorno se desfaz: evasão +4 por um tempo."),
            ["arcane-focus"] = ("Foco Arcano", "Suas magias batem mais forte (+3) e falham menos (−10%) por um tempo."),
            ["levitate"] = ("Levitar", "Você flutua: armadilhas não te alcançam."),
            ["dig"] = ("Escavar", "Abre até seis casas de rocha escavável em linha."),
            ["enlarge"] = ("Aumentar", "Você cresce uma vez e meia: For +4, Con +3, +15 PV."),

            // ---- Ilusão
            ["sleep"] = ("Sono", "Põe um inimigo vivo para dormir. Os fortes resistem; dano acorda."),
            ["confuse"] = ("Confundir", "O alvo cambaleia ao acaso."),
            ["invisibility"] = ("Invisibilidade", "Inimigos perdem você de vista e acertam pior."),
            ["charm"] = ("Enfeitiçar", "Um inimigo vivo luta por você por um tempo. Difícil nos fortes."),
            ["dazzle"] = ("Ofuscar", "Um clarão que deixa o alvo cego e tropeçando."),
            ["color-spray"] = ("Leque de Cores", "Um leque de cores tonteantes, três casas de comprimento."),
            ["befuddle"] = ("Embaralhar", "Um redemoinho de besteira ao redor de um ponto: quem está nele cambaleia."),
            ["suggestion"] = ("Sugestão", "Uma ideia sussurrada: o alvo te serve por pouco tempo."),
            ["displacement"] = ("Deslocamento", "Sua imagem está um palmo fora de onde você está."),
            ["hypnotic-pattern"] = ("Padrão Hipnótico", "Um tecido de luz que põe para dormir quem está a 2 casas."),
            ["terrify"] = ("Aterrorizar", "Toda criatura a 4 casas vê seu pior medo."),
            ["phantasmal-killer"] = ("Assassino Fantasmal", "O próprio medo do alvo toma forma e ataca."),
            ["nightmare"] = ("Pesadelo", "Um pesadelo acordado: fere, e o alvo foge aterrorizado."),
            ["mass-charm"] = ("Feitiço em Massa", "Uma onda de afeto por você: toda criatura a 3 casas pode se voltar contra os amigos."),

            // ---- Necromancia
            ["drain-life"] = ("Drenar Vida", "Rouba vida: fere o alvo e cura você pela metade. Não funciona nos mortos."),
            ["raise-skeleton"] = ("Erguer Esqueleto", "Um esqueleto arranha o chão para te servir."),
            ["ossify"] = ("Ossificar", "O osso cobre sua pele: CA +4 por um tempo. O Ossuary leva um pouco de você por isso."),
            ["reshape-flesh"] = ("Remodelar Carne", "Pede um presente ao Ossuary. Você ganha uma mutação, e ele ganha uma parte de você."),
            ["marrow-bolt"] = ("Dardo de Tutano", "Um espeto de tutano frio como a cova. Bate forte; o Ossuary leva um pouco de você. Não afeta mortos."),
            ["fear"] = ("Medo", "O alvo foge aterrorizado. Mentes vazias não sentem medo."),
            ["finger-of-death"] = ("Dedo da Morte", "Desfaz os vivos com um apontar de mão."),
            ["army-of-bones"] = ("Exército de Ossos", "Três esqueletos se erguem para te guardar."),
            ["chill-touch"] = ("Toque Gélido", "Uma mão fria como a cova. Fere, e o alvo bate pior por um tempo."),
            ["bone-shard"] = ("Estilhaço de Osso", "Uma lasca de osso lançada com um estalo."),
            ["enfeeble"] = ("Enfraquecer", "Um raio cinza drena o alvo: ele sofre mais de cada golpe por um bom tempo."),
            ["wither"] = ("Definhar", "Apodrece um membro. Fere e atrasa."),
            ["vampiric-touch"] = ("Toque Vampírico", "Um toque que devolve tudo: você cura o que causa."),
            ["curse-of-weakness"] = ("Maldição da Fraqueza", "Uma maldição murmurada sobre tudo ao redor de um ponto: sofrem mais de cada golpe."),
            ["grave-chill"] = ("Frio da Cova", "O frio do cemitério te envolve: necrótico 50%, gelo 30%."),
            ["life-tap"] = ("Sangrar Vida", "Queima 8 dos seus PV em 8 de mana."),
            ["bone-hound"] = ("Cão de Ossos", "Um cão de ossos costurados corre aos seus pés."),
            ["plague-bolt"] = ("Dardo da Peste", "Um dardo verde e gorduroso. O alvo adoece por um tempo."),
            ["rotting-burst"] = ("Explosão Pútrida", "Uma bolha de podridão estoura ao redor de um ponto."),
            ["hemorrhage"] = ("Hemorragia", "Abre as veias do alvo à distância: ele sangra por um tempo."),
            ["bone-spear"] = ("Lança de Osso", "Uma lança de osso que atravessa toda criatura em linha."),
            ["dread"] = ("Pavor", "Uma onda de pavor: toda criatura a 5 casas pode fugir."),
            ["unholy-vigor"] = ("Vigor Profano", "Seus golpes trazem frio da cova (+1d4 necrótico) e te alimentam (15% de roubo de vida)."),
            ["dark-pact"] = ("Pacto Sombrio", "Poder mágico +4 por um bom tempo. O Ossuary cobra 6 pontos de corrupção."),
            ["command-undead"] = ("Comandar Mortos-Vivos", "Um morto-vivo dobra o joelho para você por um tempo."),
            ["animate-ghoul"] = ("Animar Carniçal", "Um carniçal se ergue para te servir. Está sempre faminto."),
            ["bloodlust"] = ("Sede de Sangue", "Calor vermelho atrás dos olhos: +2 para acertar, +3 de dano, um pouco de roubo de vida."),
            ["feign-death"] = ("Fingir de Morto", "Você fica imóvel e frio. Tudo por perto perde você de vista."),
            ["gravebind"] = ("Amarra da Cova", "Mãos mortas agarram quem está preso ao chão: criaturas a 2 casas ficam presas."),
            ["skull-barrage"] = ("Chuva de Crânios", "Três crânios gritando voam sobre criaturas à vista."),
            ["death-aura"] = ("Aura da Morte", "Uma mortalha de morte fria: quem te golpeia sofre 1d6 necrótico."),
            ["contagion"] = ("Contágio", "Uma doença que gruda. Tudo perto do ponto fica envenenado por muito tempo."),
            ["cloudkill"] = ("Nuvem Mortal", "Uma névoa verde assassina, três casas de largura."),
            ["siphon-soul"] = ("Sugar Alma", "Puxa um pedaço da alma do alvo para dentro de você."),
            ["death-wave"] = ("Onda da Morte", "Um anel de morte varre 3 casas ao seu redor."),
            ["banshee-wail"] = ("Lamento da Banshee", "Um grito que fere e manda os vivos correr. 4 casas."),
            ["raise-wight"] = ("Erguer Aparição", "Uma aparição em cota podre sai do escuro e se ajoelha."),
            ["bone-golem"] = ("Golem de Ossos", "Um golem de cem esqueletos, amarrados com arame, te atende."),
            ["soul-reap"] = ("Ceifar Almas", "Tudo vivo a 5 casas entrega um pedaço da alma; você fica com um quarto."),
            ["power-word-kill"] = ("Palavra de Morte", "Uma palavra. O que está muito ferido morre; o que não está leva um golpe enorme."),
            ["summon-wraith"] = ("Invocar Espectro", "Um espectro, preso a você por um tempo, atravessa a parede."),
            ["ritual-of-blood"] = ("Ritual de Sangue", "Corte-se por um quarto da sua vida; encha a mana até a borda."),

            // ---- Sagrada
            ["cure-wounds"] = ("Curar Ferimentos", "Fecha sua carne: 2d6 mais Sabedoria e nível."),
            ["bless"] = ("Abençoar", "Uma mão mais firme: +2 para acertar por bastante tempo."),
            ["smite"] = ("Punir", "Ira radiante. Os mortos-vivos sofrem o dobro."),
            ["cleanse"] = ("Purificar Corpo", "Queima veneno, confusão, cegueira e visões."),
            ["turn-undead"] = ("Expulsar Mortos-Vivos", "Todo morto-vivo à vista queima e foge."),
            ["greater-heal"] = ("Cura Maior", "Uma grande cura: 4d8 mais Sabedoria e nível."),
            ["purify"] = ("Purificar", "Queima 15 pontos de corrupção do Ossuary em você. As mutações ficam."),
            ["revive"] = ("Reviver", "Prende sua alma: a próxima morte em 300 turnos é desfeita."),
            ["minor-mending"] = ("Remendo Menor", "Uma pequena misericórdia: 1d8 mais um pouco de Sabedoria."),
            ["sacred-flame"] = ("Chama Sagrada", "A luz cai sobre o alvo como uma mão. Os mortos-vivos sofrem o dobro."),
            ["holy-light"] = ("Luz Sagrada", "Uma luz suave mostra o chão ao redor."),
            ["shield-of-faith"] = ("Escudo da Fé", "A fé se ergue como muralha: CA +4 por um tempo."),
            ["command"] = ("Ordem", "Uma única palavra, numa voz que não é sua: 'fuja'."),
            ["searing-light"] = ("Luz Abrasadora", "Uma agulha de luz branca. Os mortos-vivos sofrem o dobro."),
            ["divine-favor"] = ("Favor Divino", "+3 para acertar, +2 de dano e um dado de fogo sagrado nos golpes, por um tempo."),
            ["protection-from-evil"] = ("Proteção contra o Mal", "Um círculo de fogo branco: CA +3 e resistência necrótica 40%."),
            ["heroism"] = ("Heroísmo", "Coragem no peito: +3 para acertar, For +1."),
            ["remedy"] = ("Remédio", "Tira o veneno do sangue."),
            ["second-wind"] = ("Segundo Fôlego", "Seu fôlego e suas pernas voltam: Vigor ao máximo."),
            ["blinding-light"] = ("Luz Ofuscante", "Um cone de luz branca que deixa as vítimas cegas."),
            ["spiritual-weapon"] = ("Arma Espiritual", "Um martelo de luz luta ao seu lado por um tempo."),
            ["regeneration"] = ("Regeneração", "As feridas se fecham sozinhas: 2 PV por turno por um tempo."),
            ["sanctuary"] = ("Santuário", "Um silêncio: poucos erguerão a mão contra você."),
            ["prayer"] = ("Oração", "+2 para acertar, +2 de dano, CA +2, evasão +1."),
            ["fortitude"] = ("Fortitude", "Con +3 e +15 PV por bastante tempo."),
            ["remove-curse"] = ("Remover Maldição", "Tira a maldição de tudo que você carrega."),
            ["hammer-of-wrath"] = ("Martelo da Ira", "Um martelo de luz. Pode atordoar."),
            ["holy-lance"] = ("Lança Sagrada", "Uma lança de luz que atravessa tudo em linha."),
            ["consecrate"] = ("Consagrar", "Santifica um trecho de chão: a luz queima quem pisa nele."),
            ["hold-person"] = ("Imobilizar", "Um alvo vivo fica rígido por alguns turnos."),
            ["holy-aura"] = ("Aura Sagrada", "Um halo ofuscante: CA +3, resistência necrótica 40%, e quem te golpeia queima."),
            ["flame-strike"] = ("Golpe de Chamas", "Uma coluna de fogo do céu, 3 casas de largura."),
            ["radiant-nova"] = ("Nova Radiante", "Um anel de luz explode 3 casas ao seu redor."),
            ["exorcise"] = ("Exorcizar", "Queima e põe em fuga tudo a 5 casas. Os mortos-vivos sofrem o dobro."),
            ["sunbeam"] = ("Raio de Sol", "Uma lança de sol em linha; o que não morre, fica cego."),
            ["divine-might"] = ("Poder Divino", "For +4 e +2 de dano por um tempo."),
            ["spirit-guardians"] = ("Guardiões Espirituais", "Espíritos pálidos rodopiam ao redor, ferindo e atrasando tudo a 2 casas."),
            ["restoration"] = ("Restauração", "Uma cura profunda: 3d8 mais Sabedoria, e todo mal em você acaba."),
            ["mass-cure"] = ("Cura em Massa", "Luz curativa em você e em todo aliado a 5 casas."),
            ["judgement"] = ("Julgamento", "Um pilar de fogo branco cai: tudo a 3 casas é julgado."),
            ["guardian-angel"] = ("Anjo da Guarda", "Um guardião alado desce para lutar por você."),
            ["angelic-blessing"] = ("Bênção Angelical", "Por bastante tempo você é um pouco mais do que é."),
            ["divine-intervention"] = ("Intervenção Divina", "O céu estende a mão: vida cheia, todo mal acabado e um silêncio ao redor."),

            // ---- Natureza
            ["thorn-dart"] = ("Dardo de Espinho", "Um espinho envenenado lançado com força."),
            ["insect-swarm"] = ("Enxame de Insetos", "Uma nuvem de moscas que picam. Ferroam e fazem as criaturas se debaterem."),
            ["barkskin"] = ("Pele de Casca", "Sua pele vira casca: CA +4 por bastante tempo."),
            ["hunters-mark"] = ("Marca do Caçador", "Marca uma presa: ela sofre mais de cada golpe por bastante tempo."),
            ["herbal-poultice"] = ("Emplasto de Ervas", "Folhas amassadas numa ferida: 1d8."),
            ["antidote"] = ("Antídoto", "Uma raiz amarga que acaba com o veneno."),
            ["shillelagh"] = ("Cacete de Carvalho", "Sua arma vibra como carvalho: +2 para acertar, +3 de dano."),
            ["wild-growth"] = ("Crescimento Selvagem", "Grama brota ao redor de um ponto. Mato seco queima bem."),
            ["entangle"] = ("Enredar", "Raízes e trepadeiras agarram tudo a 2 casas."),
            ["spike-growth"] = ("Espinhos do Mato", "Espinhos rasgam quem cruza a área e atrasam."),
            ["thorns"] = ("Espinhos", "Espinhos brotam da pele: quem te acerta sofre 1d6."),
            ["rejuvenate"] = ("Rejuvenescer", "Cura 2d6 agora e um pouco a cada turno depois."),
            ["goodberries"] = ("Bagas Boas", "Um punhado de bagas: um pouco de cura e um pouco de comida."),
            ["eagle-eye"] = ("Olho de Águia", "+3 para acertar por um tempo."),
            ["camouflage"] = ("Camuflagem", "Você toma as cores da pedra: muito mais difícil de notar."),
            ["cheetah-sprint"] = ("Corrida do Guepardo", "Uma rajada curta de velocidade."),
            ["flame-blade"] = ("Lâmina de Fogo", "Uma pele de fogo na arma: +1d6 de fogo."),
            ["speak-with-animals"] = ("Falar com Animais", "Uma fera escuta e te segue por um tempo."),
            ["calm-beasts"] = ("Acalmar Feras", "Toda fera a 4 casas se deita e dorme."),
            ["hoarfrost"] = ("Geada", "Uma crosta de geada mortal num trecho de chão."),
            ["dust-devil"] = ("Redemoinho de Poeira", "Um redemoinho pequeno que bate, cega e empurra."),
            ["lightning-lash"] = ("Chicote de Raio", "Um chicote de raio vindo do céu."),
            ["fire-seeds"] = ("Sementes de Fogo", "Sementes que explodem em chamas onde caem."),
            ["poison-spray"] = ("Jato de Veneno", "Um jato de veneno de três casas."),
            ["moonfire"] = ("Fogo da Lua", "Fogo branco e frio vindo de cima. Os mortos-vivos sofrem o dobro."),
            ["summon-hawk"] = ("Invocar Falcão", "Um falcão espiritual mergulha sobre seus inimigos."),
            ["wild-leap"] = ("Salto Selvagem", "Um pulo que leva você cinco casas."),
            ["bears-endurance"] = ("Vigor do Urso", "Con +4 e +10 PV por bastante tempo."),
            ["gale"] = ("Vendaval", "Um vento uivante que bate e joga criaturas três casas para trás."),
            ["sleet-storm"] = ("Chuva de Granizo", "Granizo numa área larga: fere, atrasa e gela o chão."),
            ["stone-spikes"] = ("Espetos de Pedra", "Espetos de pedra saem num cone de quatro casas."),
            ["venom-bolt"] = ("Dardo de Veneno", "Um dardo de veneno concentrado. O veneno demora a passar."),
            ["spore-cloud"] = ("Nuvem de Esporos", "Uma nuvem de esporos: queima, e a mente vai junto."),
            ["choking-vines"] = ("Trepadeiras Sufocantes", "Uma criatura presa e apertada."),
            ["tremor"] = ("Tremor", "O chão estremece 3 casas ao seu redor: fere e pode atordoar."),
            ["commune"] = ("Comunhão com a Natureza", "A terra diz o que há por perto: o mapa a 14 casas e toda armadilha nele."),
            ["spirit-wolves"] = ("Lobos Espirituais", "Dois lobos de luz pálida caçam por você."),
            ["spirit-boar"] = ("Javali Espiritual", "Um javali espiritual avança sobre seus inimigos."),
            ["giant-spider"] = ("Aranha Espiritual", "Uma aranha espiritual, toda patas e veneno, te serve."),
            ["wolf-form"] = ("Forma de Lobo", "Você toma a forma de um lobo: For +3, Des +3, CA +2, evasão +2."),
            ["bear-form"] = ("Forma de Urso", "Você toma a forma de um urso: For +5, Con +4, +20 PV, CA +3."),
            ["eagle-form"] = ("Forma de Águia", "Você toma a forma de uma águia: Des +4, evasão +4."),
            ["tornado"] = ("Tornado", "Um funil uivante: esmaga, empurra e cega."),
            ["rockslide"] = ("Deslizamento de Pedras", "Uma chuva de pedregulhos vinda de cima."),
            ["briar-wall"] = ("Muralha de Sarças", "Uma muralha de espinhos duros como ferro brota e prende o que pega."),
            ["healing-rain"] = ("Chuva Curativa", "Uma chuva morna que cura você e todo aliado a 5 casas."),
            ["summon-bear"] = ("Invocar Urso", "Um urso espiritual lumbra para o seu lado."),
            ["lightning-storm"] = ("Tempestade de Raios", "Cinco raios em cinco criaturas à vista."),
            ["starfall"] = ("Chuva de Estrelas", "Quatro estrelas caem sobre quatro criaturas à vista."),
            ["treant"] = ("Ente", "Uma árvore velha caminha."),

            // ---- Sombra
            ["shadow-bolt"] = ("Dardo de Sombra", "Um dardo de escuridão fria. Não afeta os mortos."),
            ["throwing-knives"] = ("Facas de Arremesso", "Um movimento de pulso: três facas que você não tinha um instante atrás."),
            ["poison-dart"] = ("Dardo Envenenado", "Um dardinho, muito veneno."),
            ["blinding-powder"] = ("Pó Cegante", "Um punhado de pimenta e cinza na cara de tudo à sua frente."),
            ["venom-blade"] = ("Lâmina Venenosa", "Sua arma pinga veneno: +1d6 de veneno."),
            ["hex"] = ("Praga", "Uma praga murmurada: os pés do alvo se arrastam."),
            ["skeleton-key"] = ("Chave-Mestra", "Destranca toda porta trancada a 5 casas."),
            ["cloak-of-shadows"] = ("Manto de Sombras", "A sombra se junta a você: muito mais difícil de notar, evasão +2."),
            ["shadow-step"] = ("Passo de Sombra", "De uma sombra para outra, a seis casas."),
            ["smoke-bomb"] = ("Bomba de Fumaça", "Uma explosão de fumaça preta: inimigos a 2 casas ficam cegos e você some de vista."),
            ["mark-for-death"] = ("Marcado para Morrer", "Uma presa marcada: sofre mais de cada golpe por bastante tempo."),
            ["caltrops"] = ("Abrolhos", "Um punhado de espinhos de ferro: fere e atrasa."),
            ["cripple"] = ("Aleijar", "Um corte no tendão: o alvo manca atrás de você."),
            ["mind-spike"] = ("Espeto Mental", "Uma agulha de pensamento cravada na cabeça do alvo."),
            ["venom-spit"] = ("Cuspe Venenoso", "Um jato de veneno entre os dentes."),
            ["light-fingers"] = ("Dedos Leves", "Surrupia algumas moedas de tudo que você toca."),
            ["disarm-traps"] = ("Desarmar Armadilhas", "Desarma toda armadilha a 3 casas."),
            ["shade-strike"] = ("Golpe de Sombra", "Um cone de sombra viva que morde e assusta."),
            ["gloom"] = ("Escuridão", "Um trecho de breu: criaturas nele lutam cegas e sofrem mais."),
            ["shadow-blade"] = ("Lâmina de Sombra", "Sua arma bebe a luz: +1d6 necrótico, +2 para acertar."),
            ["vampiric-edge"] = ("Gume Vampírico", "Sua arma tem sede: um quarto do que você causa volta."),
            ["shadow-clone"] = ("Clone de Sombra", "Sua sombra se levanta do chão e luta."),
            ["umbral-grasp"] = ("Garra Umbral", "Mãos de sombra se erguem e seguram o alvo."),
            ["veil-of-darkness"] = ("Véu de Escuridão", "O escuro engrossa: tudo por perto perde você de vista."),
            ["knife-flurry"] = ("Chuva de Facas", "Três facas acham, cada uma, uma criatura à vista."),
            ["fade"] = ("Esvanecer", "Você é difícil de olhar e mais difícil de acertar: evasão +5, difícil de notar."),
            ["dread-gaze"] = ("Olhar Aterrador", "Um olhar que mostra ao alvo a própria morte."),
            ["umbral-shroud"] = ("Mortalha Umbral", "Uma mortalha escura te envolve: CA +2, necrótico 30%, gelo 20%."),
            ["night-whip"] = ("Chicote da Noite", "Um chicote de escuridão que açoita tudo em linha."),
            ["assassinate"] = ("Assassinar", "Um golpe mortal: dano em dobro em quem dorme ou está desprevenido."),
            ["black-tentacles"] = ("Tentáculos Negros", "Tentáculos de escuridão esmagam e prendem tudo a 2 casas."),
            ["void-rift"] = ("Fenda do Vazio", "Um pequeno buraco no mundo, puxando tudo perto dele."),
            ["vanish"] = ("Desaparecer", "Fumaça, um truque, e você não está aqui: invisível, e todos te perderam."),
            ["coup-de-grace"] = ("Golpe de Misericórdia", "Acaba com o que está muito ferido; um golpe firme no resto."),
            ["soul-dagger"] = ("Adaga da Alma", "Uma adaga de vida roubada; metade do que ela tira volta para você."),
            ["quicken-shadow"] = ("Acelerar Sombra", "Uma rajada curta de velocidade."),
            ["eclipse"] = ("Eclipse", "A luz morre por 5 casas: tudo nela é ferido e cego."),
            ["shadow-walk"] = ("Caminhada Sombria", "Entre na escuridão e saia em outro ponto do nível, sem ser visto."),
            ["dominate"] = ("Dominar", "Uma criatura viva se torna sua por bastante tempo."),
        };

        static void AddSpellText()
        {
            foreach (var kv in SpellPt)
            {
                var sp = Magic.Spells.Find(kv.Key);
                if (sp == null) continue;
                if (!Pt.ContainsKey(sp.Name)) Pt[sp.Name] = kv.Value.Name;
                Pt[sp.Blurb] = kv.Value.Blurb;
            }
            foreach (var b in Magic.SpellBuffs.All)
            {
                if (BuffPt.TryGetValue(b.Id, out var t)) { Pt[b.Label] = t.Item1; Pt[b.Msg] = t.Item2; }
            }
            foreach (var kv in Schools) if (!Pt.ContainsKey(kv.Key)) Pt[kv.Key] = kv.Value;
        }

        static readonly Dictionary<string, string> Schools = new Dictionary<string, string>
        {
            ["Evocation"] = "Evocação", ["Conjuration"] = "Conjuração", ["Alteration"] = "Alteração", ["Illusion"] = "Ilusão",
            ["Necromancy"] = "Necromancia", ["Sacred"] = "Sagrada", ["Nature"] = "Natureza", ["Shadow"] = "Sombra",
            ["Evo"] = "Evo", ["Con"] = "Con", ["Alt"] = "Alt", ["Ill"] = "Ilu", ["Nec"] = "Nec", ["Sac"] = "Sag", ["Nat"] = "Nat", ["Sha"] = "Som",
            ["All"] = "Tudo", ["Range"] = "Alcance", ["Around you"] = "Ao redor", ["cells"] = "casas", ["aim within"] = "mire até", ["radius"] = "raio",
            ["Casting stat"] = "Atributo", ["Wis"] = "Sab", ["armour and shield raise failure."] = "armadura e escudo aumentam a falha.", ["Damage"] = "Dano", ["level"] = "nível", ["dice"] = "dados", ["Rider"] = "Efeito",
            ["physical"] = "físico", ["fire"] = "fogo", ["cold"] = "frio", ["lightning"] = "raio", ["poison"] = "veneno", ["necrotic"] = "necrótico", ["holy"] = "sagrado",
            ["burn"] = "queimar", ["slow"] = "atrasar", ["fear"] = "medo", ["sleep"] = "sono", ["confuse"] = "confundir", ["blind"] = "cegar", ["stun"] = "atordoar", ["root"] = "prender",
            ["bleed"] = "sangrar", ["weaken"] = "enfraquecer", ["charm"] = "enfeitiçar",
            ["Up/Down  Left/Right school  Enter casts  Esc closes"] = "↑↓  ←→ escola  Enter conjura  Esc fecha",
        };

        static readonly Dictionary<string, (string, string)> BuffPt = new Dictionary<string, (string, string)>
        {
            ["mage-armor"] = ("Armadura Arcana", "Placas invisíveis de força se assentam sobre você. (CA +4)"),
            ["arcane-shield"] = ("Escudo", "Um disco de força salta à sua frente. (CA +6, por pouco tempo)"),
            ["bulls-strength"] = ("Força", "Seus músculos incham. (For +3)"),
            ["cats-grace"] = ("Graça", "Você se sente leve e rápido. (Des +3)"),
            ["foxs-cunning"] = ("Astúcia", "Seus pensamentos se afiam. (Int +3)"),
            ["owls-wisdom"] = ("Percepção", "Uma clareza calma te assenta. (Sab +3)"),
            ["endure"] = ("Suportar", "Os extremos de calor, frio e tempestade perdem a mordida."),
            ["fire-ward"] = ("Prot. Fogo", "Um véu fresco te envolve. (fogo 60%)"),
            ["frost-ward"] = ("Prot. Gelo", "Um véu morno te envolve. (frio 60%)"),
            ["storm-ward"] = ("Prot. Raio", "Seu cabelo se ergue e o raio escorrega. (raio 60%)"),
            ["arcane-focus"] = ("Foco", "O tecido da magia entra em foco. (poder mágico +3, menos falhas)"),
            ["blur"] = ("Borrão", "Seu contorno se desfaz. (evasão +4)"),
            ["displacement"] = ("Deslocado", "Sua imagem escorrega um palmo de onde você está."),
            ["enlarge"] = ("Aumentado", "Você incha até uma vez e meia seu tamanho. (For +4, Con +3, +15 PV)"),
            ["sense"] = ("Sentido", "Você sente toda coisa viva por perto."),
            ["grave-ward"] = ("Prot. Cova", "O frio de cemitério te cerca. (necrótico 50%, frio 30%)"),
            ["unholy-vigor"] = ("Profano", "Seus golpes voltam mais quentes do que saíram. (+1d4 necrótico, 15% de roubo de vida)"),
            ["dark-pact"] = ("Pacto Sombrio", "Você assina. Algo assina de volta. (poder mágico +4)"),
            ["bloodlust"] = ("Sede de Sangue", "Calor vermelho atrás dos olhos. (+2 acerto, +3 dano, 10% de roubo de vida)"),
            ["death-aura"] = ("Aura da Morte", "Uma mortalha de morte fria paira em volta de você."),
            ["regen"] = ("Regen", "Suas feridas começam a se fechar sozinhas."),
            ["sanctuary"] = ("Santuário", "Cai um silêncio ao redor. Poucos erguerão a mão contra você."),
            ["faith"] = ("Fé", "A fé se ergue como muralha. (CA +4)"),
            ["favor"] = ("Favor", "O céu se apoia no seu braço. (+3 acerto, +2 dano, +1d4 sagrado)"),
            ["holy-aura"] = ("Aura Sagrada", "Um halo ofuscante te ilumina. (CA +3; necrótico 40%; queima quem te golpeia)"),
            ["prot-evil"] = ("Protegido", "Um círculo de fogo branco te cerca. (CA +3, necrótico 40%)"),
            ["prayer"] = ("Oração", "A oração firma cada parte sua. (+2 acerto, +2 dano, CA +2)"),
            ["fortitude"] = ("Fortitude", "Você se sente difícil de matar. (Con +3, +15 PV)"),
            ["heroism"] = ("Heroísmo", "A coragem é uma brasa no peito. (+3 acerto, For +1)"),
            ["divine-might"] = ("Poder Divino", "Uma força que não é sua enche seus braços. (For +4, +2 dano)"),
            ["angelic"] = ("Angelical", "Por um tempo você é um pouco mais do que é. (tudo +2, +20 PV, resistência 30%)"),
            ["barkskin"] = ("Pele de Casca", "Sua pele se enrijece em casca. (CA +4)"),
            ["thorns"] = ("Espinhos", "Espinhos furam sua pele; quem te acerta sangra por isso."),
            ["bears-endurance"] = ("Vigor", "Você se sente teimoso como um urso. (Con +4, +10 PV)"),
            ["eagle-eye"] = ("Olho de Águia", "O mundo se afia. (+3 acerto)"),
            ["camouflage"] = ("Camuflagem", "Você toma as cores da pedra. (mais difícil de notar)"),
            ["wolf-form"] = ("Forma de Lobo", "Você cai de quatro, pernas longas e olhos brilhantes. (For +3, Des +3, CA +2)"),
            ["bear-form"] = ("Forma de Urso", "Seus ombros se alargam e as mãos viram garras. (For +5, Con +4, +20 PV, CA +3)"),
            ["eagle-form"] = ("Forma de Águia", "O ar te leva. (Des +4, evasão +4)"),
            ["flame-blade"] = ("Lâmina de Fogo", "Sua arma veste uma pele de fogo. (+1d6 fogo)"),
            ["shillelagh"] = ("Cacete", "Sua arma vibra como carvalho. (+2 acerto, +3 dano)"),
            ["shadow-cloak"] = ("Sombrio", "Sombras se juntam a você como gatos. (mais difícil de notar, evasão +2)"),
            ["venom-blade"] = ("Lâmina Venenosa", "Sua arma pinga veneno. (+1d6 veneno)"),
            ["shadow-blade"] = ("Lâmina de Sombra", "Sua arma bebe a luz. (+1d6 necrótico, +2 acerto)"),
            ["vampiric-edge"] = ("Gume Vampírico", "Sua arma tem sede. (25% de roubo de vida)"),
            ["fade"] = ("Esvanecido", "Você é difícil de olhar, mais difícil de acertar. (evasão +5)"),
            ["umbral-shroud"] = ("Mortalha Umbral", "Uma mortalha escura se dobra em volta de você. (CA +2, necrótico 30%, frio 20%)"),
        };
    }
}
