using System.Collections.Generic;

namespace Ossuary.Core
{
    /// <summary>Portuguese for the messages the play layer says: items, spells, gods, potions, traps, events, bosses. Patterns carry names through <see cref="Part"/>.</summary>
    public static partial class Loc
    {
        static void AddMsgText()
        {
            foreach (var kv in new[] {
                // commands
                ("The door is locked.", "A porta está trancada."), ("The shelves are bare.", "As prateleiras estão vazias."), ("There is no door here.", "Não há porta aqui."),
                ("There is no one here to trade with.", "Não há ninguém aqui para negociar."), ("There is nothing to open here.", "Não há nada para abrir aqui."),
                ("There is nothing to open.", "Não há nada para abrir."), ("You abandon the run.", "Você abandona a expedição."), ("You are asleep.", "Você está dormindo."),
                ("You are not carrying anything.", "Você não está carregando nada."), ("You are not wearing any rings or amulet.", "Você não usa anéis nem amuleto."),
                ("You are not wearing armour.", "Você não está de armadura."), ("You are stunned.", "Você está atordoado."),
                ("You cannot move that way here.", "Você não pode ir por ali aqui."), ("You have nothing to sell.", "Você não tem nada para vender."),
                ("You kick the rubble away.", "Você chuta os escombros para longe."), ("You open the door.", "Você abre a porta."),
                ("You shift the rubble aside.", "Você afasta os escombros."), ("Your hands are already full of rings.", "Suas mãos já estão cheias de anéis."),
                ("Your hands are already full.", "Suas mãos já estão cheias."),
                // abilities
                ("Not on your own ally.", "Não no seu próprio aliado."), ("That is out of reach.", "Isso está fora de alcance."), ("That is out of range.", "Isso está fora de alcance."),
                ("There is nowhere to use that.", "Não há onde usar isso."), ("You are too winded.", "Você está sem fôlego."), ("You cannot focus.", "Você não consegue se concentrar."),
                ("You have no clear shot.", "Você não tem linha de tiro livre."), ("You have no clear line there.", "Você não tem linha livre até ali."),
                ("You have no such ability.", "Você não tem essa habilidade."), ("You melt into the shadows.", "Você se funde às sombras."),
                ("You need a shield for that.", "Você precisa de um escudo para isso."), ("Your blade cuts only air.", "Sua lâmina corta apenas o ar."),
                // bosses
                ("The Ashen Regent exhales. The floor around it ignites.", "O Regente de Cinzas exala. O chão ao redor se incendeia."),
                ("The Drowned King beats his trident on the stone. Black water spreads.", "O Rei Afogado bate o tridente na pedra. Água negra se espalha."),
                ("The Gaoler's chain bites into you and drags you in!", "A corrente do Carcereiro morde você e te arrasta!"),
                ("The Stone Warden slams the floor. The ground jumps.", "O Guardião de Pedra golpeia o chão. O solo salta."),
                // Every branch boss, word for word (Game.Bosses.cs): what waits at the bottom, what it does when it
                // is half dead, and what is left when it falls. The names are proper nouns and stay.
                ("Chains drag somewhere ahead. The Gaoler keeps the way out, and he has not opened a cell in a long time.",
                    "Correntes se arrastam em algum lugar à frente. O Carcereiro guarda a saída, e não abre uma cela há muito tempo."),
                ("The Gaoler howls for his hounds.", "O Carcereiro uiva por seus cães."),
                ("The Gaoler's keys clatter across the stone.", "As chaves do Carcereiro tilintam pela pedra."),
                ("The floor hums. The Stone Warden never left the post the dwarves gave it.",
                    "O chão zumbe. O Guardião de Pedra nunca deixou o posto que os anões lhe deram."),
                ("The Stone Warden cracks, and moves faster.", "O Guardião de Pedra racha e se move mais rápido."),
                ("The Stone Warden crumbles into ordinary rock.", "O Guardião de Pedra se desfaz em pedra comum."),
                ("Squeaking, everywhere, in the walls. The Rat King is holding court.", "Guinchos por toda parte, dentro das paredes. O Rei dos Ratos dá audiência."),
                ("The Rat King screams, and the walls scream back.", "O Rei dos Ratos grita, e as paredes gritam de volta."),
                ("The Rat King dies, and the Warrens go quiet.", "O Rei dos Ratos morre, e as Tocas ficam quietas."),
                ("Black water rises to your ankles. The Drowned King has been waiting under it.",
                    "Água negra sobe até seus tornozelos. O Rei Afogado esperava sob ela."),
                ("The Drowned King lifts his trident. The water answers.", "O Rei Afogado ergue o tridente. A água responde."),
                ("The Drowned King sinks, finally, and the water goes still.", "O Rei Afogado afunda, enfim, e a água fica parada."),
                ("The last room of the Annex is a ledger, and the Warden is reading it aloud: your name, your debts, your sins.",
                    "A última sala do Anexo é um livro-razão, e o Guardião o lê em voz alta: seu nome, suas dívidas, seus pecados."),
                ("The Annex Warden closes the ledger. The dead in the walls stand up.",
                    "O Guardião do Anexo fecha o livro-razão. Os mortos nas paredes se levantam."),
                ("The Annex Warden crumples, and every debt you owed is struck out at once.",
                    "O Guardião do Anexo desmorona, e toda dívida sua é riscada de uma vez."),
                ("The air at the top of the Spire is thick enough to chew. The Ashen Regent is not hungry. It is angry.",
                    "O ar no alto da Torre é espesso o bastante para mastigar. O Regente de Cinzas não está com fome. Está furioso."),
                ("The Ashen Regent splits its crown, and the cinders stand up.", "O Regente de Cinzas parte a coroa, e as brasas se levantam."),
                ("The Ashen Regent comes apart like a log in a fire.", "O Regente de Cinzas se desfaz como um tronco no fogo."),
                // crime
                ("The animal wants no part of it.", "O animal não quer saber disso."), ("There is no point.", "Não adianta."),
                // events
                ("\"A pleasure,\" says the man in the nice coat, and means none of it.", "\"Um prazer\", diz o homem de casaco bonito, sem sentir nada disso."),
                ("\"Not a word,\" says the driver, and takes your coin with two fingers.", "\"Nem uma palavra\", diz o condutor, e pega sua moeda com dois dedos."),
                ("A little blue bottle. The driver does not meet your eye.", "Um frasquinho azul. O condutor não encontra seu olhar."),
                ("It takes an hour and a borrowed spade. You say the words you remember.", "Leva uma hora e uma pá emprestada. Você diz as palavras de que se lembra."),
                ("Nothing but ash and a child's boot.", "Nada além de cinzas e uma bota de criança."), ("The ash in the bowl warms for a moment.", "As cinzas na tigela esquentam por um momento."),
                ("The ash is only ash, but you feel remembered.", "As cinzas são só cinzas, mas você se sente lembrado."),
                ("They look at each other, and at the empty road behind you, and step aside.", "Eles se entreolham, olham a estrada vazia atrás de você e saem do caminho."),
                ("Two rations, still wrapped.", "Duas rações, ainda embrulhadas."), ("Two rations, wrapped in waxed cloth.", "Duas rações, embrulhadas em pano encerado."),
                ("You have nothing to give.", "Você não tem nada para dar."),
                ("You sleep by the dead fire, one eye open. Nothing comes. (8 hours)", "Você dorme junto à fogueira apagada, com um olho aberto. Nada vem. (8 horas)"),
                // gods
                ("A few coins are not an offering.", "Algumas moedas não são uma oferenda."), ("Khorr finds your hands empty and gives nothing.", "Khorr vê suas mãos vazias e nada dá."),
                ("The shadows lean in and keep your secret.", "As sombras se aproximam e guardam seu segredo."), ("There is no room for Nhal's servants.", "Não há lugar para os servos de Nhal."),
                ("There is nothing left in you for Mourne to give.", "Não resta nada em você que Mourne possa dar."),
                ("Veyra breathes on your hands. Your blows will burn.", "Veyra sopra sobre suas mãos. Seus golpes vão queimar."),
                ("Warm light pours through you. Aurel makes you whole.", "Uma luz morna te atravessa. Aurel te restaura."), ("You cannot pay the tribute.", "Você não pode pagar o tributo."),
                ("You have nothing to offer.", "Você não tem nada a oferecer."), ("You have nothing to sacrifice.", "Você não tem nada para sacrificar."),
                ("Your weapon can hold no more of Khorr's regard.", "Sua arma não suporta mais da estima de Khorr."),
                // items
                ("Fire erupts around you, and passes harmlessly overhead.", "O fogo irrompe ao seu redor e passa inofensivo por cima."), ("Nothing happens.", "Nada acontece."),
                ("Something vast shifts its attention elsewhere.", "Algo imenso desvia a atenção para outro lugar."), ("The ground trembles and dust falls from the ceiling.", "O chão treme e poeira cai do teto."),
                ("The pull fades before it takes hold.", "A atração some antes de agarrar."), ("The scroll is blank.", "O pergaminho está em branco."),
                ("The shape of this level floods your mind.", "A forma deste nível inunda sua mente."), ("The wall crumbles to rubble!", "A parede se desfaz em escombros!"),
                ("The wand flares with light!", "A varinha explode em luz!"), ("The wand is spent.", "A varinha está esgotada."), ("The world folds around you.", "O mundo se dobra ao seu redor."),
                ("There is nothing to dig there.", "Não há nada para cavar ali."), ("You are not wearing armour. Nothing happens.", "Você não está de armadura. Nada acontece."),
                ("You are yanked across the level!", "Você é arrancado através do nível!"), ("You feel a surge of insight.", "Você sente uma onda de intuição."),
                ("You feel strangely refreshed.", "Você se sente estranhamente revigorado."), ("You feel the weight of a thousand eyes turn toward you.", "Você sente o peso de mil olhos se voltando para você."),
                ("You find nothing to confuse.", "Você não encontra nada para confundir."),
                // spells
                ("A calm certainty steadies your hand. (+2 to hit)", "Uma certeza calma firma sua mão. (+2 para acertar)"),
                ("A clean light burns the Ossuary out of you. (-15 corruption)", "Uma luz limpa queima o Ossuary para fora de você. (-15 de corrupção)"),
                ("A clean light burns the sickness out of you.", "Uma luz limpa queima a doença para fora de você."), ("A pale shimmer wraps around you. (AC +3)", "Um brilho pálido envolve você. (CA +3)"),
                ("A wall of flame roars up.", "Uma parede de chamas ruge."), ("Black oil seeps across the floor.", "Óleo negro escorre pelo chão."),
                ("Bone creeps over your skin. (AC +4)", "Osso cresce sobre sua pele. (CA +4)"), ("No undead stir in your sight.", "Nenhum morto-vivo se move à sua vista."),
                ("Space wrenches around you...", "O espaço se contorce ao seu redor..."), ("The blast lands on empty ground.", "A explosão cai em terreno vazio."),
                ("The bolt crackles away down the passage.", "O raio crepita pelo corredor."), ("The spell fades with no effect.", "A magia se desfaz sem efeito."),
                ("The world folds; you step through.", "O mundo se dobra; você atravessa."), ("The world slows around you.", "O mundo desacelera ao seu redor."),
                ("There is nothing left in you to reshape.", "Não resta nada em você para remodelar."), ("Water wells up from the stone.", "Água brota da pedra."),
                ("You fade from sight.", "Você some da vista."), ("Your skin turns to stone. (AC +6)", "Sua pele vira pedra. (CA +6)"),
                ("Your soul is bound to this flesh. (the next death is undone)", "Sua alma está presa a esta carne. (a próxima morte é desfeita)"),
                ("A puff of smoke, and you are gone.", "Uma nuvem de fumaça, e você some."), ("Heaven takes a hand. You are whole.", "O céu estende a mão. Você está inteiro."),
                ("Light blooms around you.", "A luz floresce ao seu redor."), ("The dark thickens around you.", "A escuridão se adensa ao seu redor."),
                ("The poison leaves your blood.", "O veneno deixa seu sangue."), ("The spell finds nowhere to send it.", "A magia não encontra para onde enviá-lo."),
                ("There is nothing in view to strike.", "Não há nada à vista para golpear."), ("You are not poisoned.", "Você não está envenenado."),
                ("You are too weak to spare it.", "Você está fraco demais para poupar isso."), ("You burn some of yourself for mana. (+8 Mp, -8 HP)", "Você queima parte de si por mana. (+8 Mp, -8 PV)"),
                ("You go still and cold. They lose track of you.", "Você fica imóvel e frio. Eles perdem você de vista."), ("Your breath comes back to you.", "Seu fôlego volta."),
                ("Pick a direction.", "Escolha uma direção."), ("The symbols mean nothing to you; you have no gift for magic.", "Os símbolos nada significam para você; você não tem dom para a magia."),
                ("There is no place to cast here.", "Não há lugar para conjurar aqui."), ("There is no room to call anything here.", "Não há espaço para invocar nada aqui."),
                ("You already know everything in this book.", "Você já conhece tudo neste livro."), ("You cannot go there.", "Você não pode ir até lá."),
                ("You cannot read like this.", "Você não consegue ler assim."), ("You cannot study with an enemy in view.", "Você não consegue estudar com um inimigo à vista."),
                ("You do not have the mana.", "Você não tem mana."), ("You do not know that spell.", "Você não conhece essa magia."),
                // potions
                ("Colours crawl across your eyes.", "Cores rastejam diante dos seus olhos."), ("Everything spins.", "Tudo gira."), ("It was poison!", "Era veneno!"),
                ("Oil slops over the floor around you.", "Óleo escorre pelo chão ao seu redor."), ("You doze off...", "Você cochila..."),
                ("You drink it. Nothing much happens.", "Você bebe. Nada de mais acontece."), ("You feel completely whole. (+2 max HP)", "Você se sente completamente inteiro. (+2 PV máx)"),
                ("You feel healthier!", "Você se sente mais saudável!"), ("You feel more charming!", "Você se sente mais encantador!"), ("You feel more experienced!", "Você se sente mais experiente!"),
                ("You feel nimbler!", "Você se sente mais ágil!"), ("You feel smarter!", "Você se sente mais esperto!"), ("You feel stronger!", "Você se sente mais forte!"),
                ("You feel wiser!", "Você se sente mais sábio!"), ("You rise off the floor. Traps cannot reach you.", "Você flutua acima do chão. Armadilhas não te alcançam."),
                ("You wake up.", "Você acorda."), ("Your eyes tingle. Nothing new is revealed.", "Seus olhos formigam. Nada de novo se revela."),
                ("Your thoughts clear and the well of mana fills.", "Seus pensamentos clareiam e o poço de mana se enche."),
                // rpg
                ("Unknown advancement.", "Evolução desconhecida."), ("You have no advancements to spend. Gain more experience first.", "Você não tem evoluções para gastar. Ganhe mais experiência antes."),
                // surfaces
                ("The flames die down.", "As chamas diminuem."), ("The flames go out.", "As chamas se apagam."), ("The shock runs through the water!", "O choque corre pela água!"),
                ("The water puts you out.", "A água apaga você."), ("You catch fire!", "Você pega fogo!"),
                // targeting
                ("That cannot be dug through.", "Não dá para cavar isso."), ("There is nothing there.", "Não há nada ali."), ("There is nothing to dig here.", "Não há nada para cavar aqui."),
                ("You cannot dig there.", "Você não pode cavar ali."), ("You cannot shoot yourself.", "Você não pode atirar em si mesmo."), ("You do not have a clear shot.", "Você não tem linha de tiro livre."),
                ("You have nothing to dig with.", "Você não tem com que cavar."), ("You loose an arrow into empty air.", "Você solta uma flecha no ar vazio."), ("You would hit your ally.", "Você acertaria seu aliado."),
                // game
                ("A shrill alarm echoes!", "Um alarme estridente ecoa!"), ("A white light drags you back from the dark!", "Uma luz branca te arrasta de volta da escuridão!"),
                ("Flames flare around you!", "Chamas surgem ao seu redor!"), ("The amulet blazes, shatters, and you wake whole.", "O amuleto arde, se estilhaça, e você acorda inteiro."),
                ("The amulet tightens around your throat!", "O amuleto aperta sua garganta!"), ("The dart poisons you!", "O dardo envenena você!"), ("The noise carries through the halls.", "O barulho se espalha pelos salões."),
                ("The poison finally wears off.", "O veneno finalmente passa."), ("The visions fade.", "As visões se esvaem."), ("This door is locked.", "Esta porta está trancada."),
                ("You are caught in a web and shake free slowly.", "Você fica preso numa teia e se solta devagar."), ("You are getting hungry.", "Você está ficando com fome."),
                ("You are starving.", "Você está morrendo de fome."), ("You can see again.", "Você volta a enxergar."), ("You fall into a hole!", "Você cai num buraco!"),
                ("You feel a chill. It is not a place to linger.", "Você sente um arrepio. Não é lugar para se demorar."), ("You feel a wrenching pull...", "Você sente um puxão violento..."),
                ("You feel less confused.", "Você se sente menos confuso."), ("You find a secret door and open it.", "Você acha uma porta secreta e a abre."), ("You slip on the ice!", "Você escorrega no gelo!"),
                ("The Elder was right: the Amulet is a seal, and you carry it.", "O Ancião tinha razão: o Amuleto é um selo, e você o carrega."),
                ("revered", "reverenciado"), ("trusted", "confiável"), ("known", "conhecido"), ("distrusted", "desconfiado"), ("hated", "odiado"),
                ("Attributes", "Atributos"), ("none", "nenhuma"),
                ("Race", "Raça"),
                // race and class descriptions
                ("Short-lived and stubborn. No gift, no curse; the dungeon's oldest tenants.", "De vida curta e teimosos. Sem dom, sem maldição; os inquilinos mais antigos da masmorra."),
                ("Deepwrought and thick-skinned. Hardy, grim, bad at small talk.", "Forjados nas profundezas e de pele grossa. Resistentes, sombrios, ruins de conversa fiada."),
                ("Quick, keen and fragile. Remembers the Age of Cities as yesterday.", "Rápidos, aguçados e frágeis. Lembram da Era das Cidades como se fosse ontem."),
                ("Small, lucky and underestimated. Walks quietly, eats well.", "Pequenos, sortudos e subestimados. Andam em silêncio e comem bem."),
                ("Barracks-born. Heavy hands, short temper, hard to put down.", "Nascidos em quartéis. Mãos pesadas, pavio curto, difíceis de derrubar."),
                ("Tinkers and scholars of the sunken archives. Clever, slight, curious.", "Inventores e eruditos dos arquivos afundados. Espertos, franzinos, curiosos."),
                ("Touched by the Spire's fire. Grey skin, warm blood, cold company.", "Tocados pelo fogo da Torre. Pele cinzenta, sangue quente, companhia fria."),
                ("No destiny yet. Average at everything, owed nothing.", "Sem destino ainda. Mediano em tudo, sem dever nada."),
                ("Holds the line. Strong and hardy, slow to learn magic.", "Segura a linha. Forte e resistente, lento para aprender magia."),
                ("Strikes from the dark. Quick hands, light armour, keen eyes.", "Ataca da escuridão. Mãos rápidas, armadura leve, olhos aguçados."),
                ("Anointed to endure. Wise, sturdy, and hard to poison with prayer.", "Ungido para resistir. Sábio, robusto e difícil de envenenar com preces."),
                ("Traded muscle for study. Frail, brilliant, already half-attuned.", "Trocou músculos por estudo. Frágil, brilhante, já meio sintonizado."),
                ("Hunts what hunts others. Patient, sure-handed, at home outdoors.", "Caça o que caça os outros. Paciente, de mão firme, à vontade ao ar livre."),
                ("Sworn to a god that may be dead. Armoured, devout, uncompromising.", "Jurado a um deus que talvez esteja morto. Blindado, devoto, intransigente."),
                ("Studies the dead because the dead keep their secrets. Pale, patient.", "Estuda os mortos porque os mortos guardam seus segredos. Pálido, paciente."),
                ("The air grows cold and the walls turn to living stone.", "O ar esfria e as paredes viram pedra viva."),
                ("Something has been living here a long time.", "Algo vive aqui há muito tempo."),
                ("Black water drips from a ceiling you cannot see.", "Água negra pinga de um teto que você não vê."),
                ("The stone here is warm, and it should not be.", "A pedra aqui está quente, e não deveria."),
                ("A door that should not have opened, and has, and has closed behind you.", "Uma porta que não deveria ter aberto, e abriu, e se fechou atrás de você."),
                ("to hit", "para acertar"), ("damage", "de dano"), ("evasion", "de evasão"), ("spell power", "de poder mágico"), ("spell focus", "de foco mágico"), ("stealth", "de furtividade"),
                // quarterstaff with an imbued spell has this literal name
                ("quarterstaff of...", "bordão de..."),
                // the same spell named inside a sentence ("Your staff flares: magic missile!"), where the composer
                // writes it in lower case
                ("magic missile", "míssil mágico"),
                // ---- what a spell says when it finds nothing, and the other one-line messages of the play layer
                ("Your roar echoes, and nothing flees.", "Seu rugido ecoa, e nada foge."),
                ("Your empty hands tingle.", "Suas mãos vazias formigam."),
                ("Your skin prickles, but you wear nothing to enchant.", "Sua pele arrepia, mas você não veste nada para encantar."),
                ("Nothing living stirs near you.", "Nada vivo se mexe por perto."), ("No beasts answer.", "Nenhuma fera responde."),
                ("The spell lands on empty ground.", "A magia cai em chão vazio."), ("The spell takes hold.", "A magia se firma."),
                ("The land shows you its shape.", "A terra mostra a sua forma."), ("No traps nearby.", "Nenhuma armadilha por perto."),
                ("There is no trap to disarm here.", "Não há armadilha para desarmar aqui."), ("Nothing here is locked.", "Nada aqui está trancado."),
                ("There is nothing there to dig.", "Não há nada para cavar ali."), ("Nothing you carry is cursed.", "Nada do que você carrega está amaldiçoado."),
                ("The water boils away in a scream of steam.", "A água ferve num grito de vapor."),
                ("Steam hisses up from the stone, and thins to nothing.", "Vapor sibila da pedra e se desfaz."),
                ("The door slams shut.", "A porta bate."), ("The door swings open.", "A porta se abre."),
                // a road fight opens by saying what provoked it
                ("Something has been living down there", "Algo viveu lá embaixo"),
                ("The one with the nice coat steps back, and the other two do not", "O de casaco bonito recua, e os outros dois não"),
                ("The stone remembers you.", "A pedra lembra de você."), ("which item?", "qual item?"),
                // what the bolt of a wand is called before it strikes or misses (Game.Items.cs)
                ("A frost ray", "Um raio de gelo"), ("A bolt of lightning", "Um raio"),
                ("A gout of flame", "Um jato de chama"), ("A silver bolt", "Um dardo prateado"),
                // an effect that slams a creature into a wall names that first ("It slams into the wall: ...")
                ("It slams into the wall:", "Bate na parede:"),
                // an aura that answers a blow: one row per retaliating buff (Game.Magic.Recipes.cs)
                ("Your thorns lashes", "Espinhos rasgam"), ("Your death aura lashes", "A aura da morte açoita"),
                ("Your holy aura lashes", "A aura sagrada açoita"),
            })
                P(kv.Item1, kv.Item2);

            // spell-hit verbs: "Flames lash the jackal for 5 damage."
            foreach (var kv in new[] {
                ("A lance of ice pierces", "Uma lança de gelo perfura"), ("A marrow spike drives into", "Um espeto de tutano se crava em"), ("A pointed finger unmakes", "Um dedo apontado desfaz"),
                ("A ray of frost hits", "Um raio de gelo acerta"), ("A single word unmakes", "Uma só palavra desfaz"), ("A word of death strikes", "Uma palavra de morte atinge"),
                ("Bolts of force strike", "Raios de força atingem"), ("Flames lash", "Chamas açoitam"), ("Holy light sears", "Luz sagrada queima"), ("Life tears out of", "A vida se rasga de"),
                ("Light sears", "A luz queima"), ("Lightning arcs into", "Um raio salta contra"), ("Lightning strikes", "Um raio atinge"), ("Lightning tears through", "Um raio rasga"),
                ("Magic strikes", "A magia atinge"), ("Radiance scours", "O brilho fustiga"), ("Scalding steam sears", "Vapor escaldante queima"), ("Steam hisses over", "O vapor sibila sobre"),
                ("The lightning leaps to", "O raio salta para"), ("The magic leaps to", "A magia salta para"), ("You cut", "Você corta"), ("You finish", "Você termina"),
                ("You open the throat of", "Você abre a garganta de"), ("You stab", "Você apunhala"), ("A meteor crushes", "Um meteoro esmaga"), ("Fire engulfs", "O fogo envolve"),
                // The rest of the verbs a spell or a surface can strike with: each one is written so that the object of
                // the sentence follows it, and the contractions of Loc.Contract join them ("em o" -> "no", "de o" -> "do").
                ("A bone shard hits", "Um estilhaço de osso atinge"), ("A bone spear skewers", "Uma lança de osso empala"),
                ("A cold hand grips", "Uma mão fria aperta"), ("A column of fire falls on", "Uma coluna de fogo cai sobre"),
                ("A cut hobbles", "Um corte aleija"), ("A dart pricks", "Um dardo espeta"), ("A dead hand drags", "Uma mão morta arrasta"),
                ("A dust devil lashes", "Um redemoinho de pó açoita"), ("A falling star crushes", "Uma estrela cadente esmaga"),
                ("A fire seed bursts on", "Uma semente de fogo explode em"), ("A flame arrow burns", "Uma flecha em chamas queima"),
                ("A gust slams into", "Uma rajada bate em"), ("A hammer of light smashes", "Um martelo de luz esmaga"),
                ("A knife bites", "Uma faca morde"), ("A lance of light pierces", "Uma lança de luz perfura"),
                ("A lash of lightning strikes", "Um açoite de raio atinge"), ("A missile of force strikes", "Um dardo de força atinge"),
                ("A nightmare rends", "Um pesadelo rasga"), ("A phantom claws", "Um fantasma arranha"),
                ("A piece of soul tears from", "Um pedaço de alma se arranca de"), ("A pillar of light falls on", "Um pilar de luz cai sobre"),
                ("A scorching ray burns", "Um raio escaldante queima"), ("A searing orb bursts on", "Uma esfera escaldante explode em"),
                ("A shadow bolt rips", "Um dardo de sombra rasga"), ("A skull bites", "Uma caveira morde"), ("A snare bites", "Uma armadilha morde"),
                ("A soul bolt tears at", "Um dardo de alma rasga"), ("A soul dagger pierces", "Uma adaga de alma perfura"),
                ("A spark leaps into", "Uma faísca salta em"), ("A spectral horror claws", "Um horror espectral arranha"),
                ("A spike of thought pierces", "Um espeto de pensamento perfura"), ("A stone shard hits", "Um estilhaço de pedra atinge"),
                ("A thorn pricks", "Um espinho espeta"), ("A wail flays", "Um lamento fustiga"),
                ("A whip of night lashes", "Um chicote da noite açoita"), ("A wire bites", "Um arame morde"),
                ("Acid splashes", "O ácido respinga"), ("An arc of lightning scorches", "Um arco de raio queima"),
                ("An ember sears", "Uma brasa queima"), ("An ice comet shatters on", "Um cometa de gelo se estilhaça em"),
                ("Black tentacles crush", "Tentáculos negros esmagam"), ("Blight withers", "A praga resseca"),
                ("Blood bursts from", "O sangue irrompe de"), ("Bone ribs crush", "Costelas de osso esmagam"),
                ("Boulders crush", "Pedras esmagam"), ("Briars tear", "Sarças rasgam"), ("Caltrops pierce", "Estrepes furam"),
                ("Coloured light flays", "Luz colorida fustiga"), ("Dark hands crush", "Mãos escuras esmagam"),
                ("Darkness crushes", "A escuridão esmaga"), ("Dead hands rake", "Mãos mortas rasgam"),
                ("Death washes over", "A morte passa por"), ("Flame washes over", "A chama passa por"), ("Flies sting", "Moscas ferroam"),
                ("Forked lightning strikes", "Um raio bifurcado atinge"), ("Frost bites", "O gelo morde"),
                ("Frostwind flays", "O vento gélido fustiga"), ("Hail hammers", "O granizo martela"),
                ("Hallowed light burns", "Luz consagrada queima"), ("Hoarfrost bites", "A geada morde"),
                ("Holy fire scours", "O fogo sagrado fustiga"), ("Judgement falls on", "O julgamento cai sobre"),
                ("Killing frost sweeps over", "A geada mortal varre"), ("Knives bite", "Facas mordem"),
                ("Lightning falls on", "Um raio cai sobre"), ("Lightning smites", "Um raio golpeia"),
                ("Magma washes over", "O magma passa por"), ("Miasma chokes", "O miasma sufoca"),
                ("Molten rock splashes", "Rocha derretida respinga"), ("Moonfire falls on", "Fogo lunar cai sobre"),
                ("Nightshade burns", "A beladona queima"), ("Plague eats into", "A peste corrói"),
                ("Radiance washes over", "O brilho passa por"), ("Rime blasts", "A geada golpeia"), ("Rot spatters", "A podridão respinga"),
                ("Rot spreads through", "A podridão se espalha por"), ("Sacred flame falls on", "A chama sagrada cai sobre"),
                ("Searing light burns", "Luz escaldante queima"), ("Shadow clamps on", "A sombra se agarra a"),
                ("Shadows bite", "Sombras mordem"), ("Sickness racks", "A doença torce"), ("Sleet lashes", "A chuva gelada açoita"),
                ("Spirits tear at", "Espíritos rasgam"), ("Spores burn", "Esporos queimam"),
                ("Static lightning shocks", "Um raio estático eletriza"), ("Stone spikes impale", "Espetos de pedra empalam"),
                ("Sunlight burns", "A luz do sol queima"), ("Sunlight scours", "A luz do sol fustiga"),
                ("The damned wail through", "Os condenados uivam por"), ("The fog chokes", "A névoa sufoca"),
                ("The gale hammers", "O vendaval martela"), ("The green ray unmakes", "O raio verde desfaz"),
                ("The ground blazes under", "O chão arde sob"), ("The ground heaves under", "O chão se ergue sob"),
                ("The ground shudders under", "O chão treme sob"), ("The poison cloud chokes", "A nuvem de veneno sufoca"),
                ("The rift tears at", "A fenda rasga"), ("The sun lance pierces", "A lança solar perfura"),
                ("The tide slams into", "A maré bate em"), ("The tornado flings", "O tornado arremessa"),
                ("Thorns rake", "Espinhos rasgam"), ("Thunder batters", "O trovão golpeia"), ("Thunder strikes", "O trovão atinge"),
                ("Venom eats", "O veneno corrói"), ("Venom spatters", "O veneno respinga"), ("Venom sprays", "O veneno espirra"),
                ("Vines crush", "Vinhas esmagam"), ("Wasps sting", "Vespas ferroam"), ("White fire cleanses", "O fogo branco purifica"),
                ("Your scythe of dark passes through", "Sua foice sombria atravessa"), ("Your touch drinks from", "Seu toque bebe de") })
                P(kv.Item1, kv.Item2);

            var front = new List<(System.Text.RegularExpressions.Regex, string)>
            {
                // commands
                R(@"You are now wearing (.+) \(AC (\d+)\)\.", "Você veste {a1} (CA $2)."),
                R(@"You cannot carry a shield with (.+) in both hands\.", "Você não pode levar um escudo com {a1} nas duas mãos."),
                R(@"You cannot wield (.+) with a shield on your arm\.", "Você não pode empunhar {a1} com um escudo no braço."),
                R(@"You cannot work out how to use (.+)\.", "Você não sabe como usar {a1}."),
                R(@"You drop (.+)\.", "Você larga {a1}."),
                R(@"You find a secret door at \((\d+),(\d+)\)\.", "Você acha uma porta secreta em ($1,$2)."),
                R(@"You hang (.+) around your neck\.", "Você pendura {a1} no pescoço."),
                R(@"You have (\d+) experience to spend\.", "Você tem $1 de experiência para gastar."),
                R(@"You pick up (.+)\.", "Você pega {a1}."),
                R(@"You remove (.+)\.", "Você tira {a1}."),
                R(@"You slip on (.+)\. It may not do anything\.", "Você enfia {a1} no dedo. Pode não fazer nada."),
                R(@"You slip on (.+)\.", "Você enfia {a1} no dedo."),
                R(@"The seed is the save: (.+)", "A semente é o save: $1"),
                // abilities
                R(@"(.+) needs a foe to aim at\.", "$1 precisa de um inimigo como alvo."),
                R(@"(.+) needs a creature to aim at\.", "$1 precisa de uma criatura como alvo."),
                R(@"(.+) needs (\d+) Vigor \(you have (\d+)\)\.", "$1 exige $2 de Vigor (você tem $3)."),
                R(@"The (.+) reels\.", "$1 cambaleia."),
                // bosses and events
                R(@"It was guarding (\d+) gold and two potions\.", "Guardava $1 de ouro e duas poções."),
                R(@"Lightning leaps from the Drowned King's trident into the water at your feet\. \(-(\d+)\)", "Um raio salta do tridente do Rei Afogado para a água aos seus pés. (-$1)"),
                R(@"The Warden reads out a debt of yours, and takes it in blood\. \(-(\d+)\)", "O Guardião lê uma dívida sua e a cobra em sangue. (-$1)"),
                R(@"The blast sears you\. \(-(\d+)\)", "A explosão queima você. (-$1)"),
                R(@"The shockwave throws you down\. \(-(\d+)\)", "A onda de choque derruba você. (-$1)"),
                R(@"A buried strongbox\. (\d+) gold\.", "Um cofre enterrado. $1 de ouro."),
                R(@"A snare in the pack bites your hand\. \(-(\d+)\)", "Uma armadilha na mochila morde sua mão. (-$1)"),
                R(@"The wall comes down on your arm\. \(-(\d+)\)", "O muro desaba sobre seu braço. (-$1)"),
                R(@"They are not fooled, and they are not gentle\. \(-(\d+) gold\)", "Eles não se deixam enganar, e não são gentis. (-$1 de ouro)"),
                R(@"Under the stair: (.+)\.", "Sob a escada: $1."),
                R(@"Under the torn tent: (\d+) gold\.", "Sob a tenda rasgada: $1 de ouro."),
                R(@"(\d+) gold, and a feeling you cannot put down\.", "$1 de ouro, e uma sensação que você não consegue largar."),
                R(@"(.+)\. A (.+) blocks your path!", "$1. Algo barra seu caminho: {u2}!"),
                // summoning, monsters fighting each other, and the altar of a rival god
                R(@"A (.+) answers your call\.", "Uma criatura atende ao seu chamado: {a1}."),
                R(@"(\d+) (.+)s answer your call\.", "Criaturas atendem ao seu chamado ($1): {a2}."),
                // a boss calls its own creatures out of the dark (Game.Bosses.cs): the boss is a proper noun, the
                // creature is not
                R(@"A (.+) answers the (.+)\.", "{a1} atende a {a2}."),
                R(@"(\d+) (.+)s answer the (.+)\.", "Criaturas atendem a {a3} ($1): {a2}."),
                // the shade of a dead hero the bones remember (Bones.cs): a name built out of another name
                R(@"shade of (.+)", "sombra de $1"),
                R(@"The (.+) fights the (.+): (\d+) damage\.", "{a1} luta contra {a2}: $3 de dano."),
                R(@"The (.+) swings at the (.+) and misses\.", "{a1} golpeia {a2} e erra."),
                R(@"Defile the altar of (.+) \(for (.+)\)", "Profanar o altar de $1 (para $2)"),
                R(@"You serve (\d+) day\(s\) in the cells\. The Watch strikes your name from its book\.", "Você cumpre $1 dia(s) nas celas. A Guarda risca seu nome do livro."),
                R(@"The (.+) falls to the (.+)\.", "$1 cai diante {d2}."),
                // gods
                R(@"The stone hums\. Your (.+) is made stronger\.", "A pedra zumbe. Seu equipamento ($1) fica mais forte."),
                R(@"You kneel and pray to (.+)\.", "Você se ajoelha e reza a $1."),
                R(@"You lay (\d+) gold on the altar\. (.+) takes it without a word\.", "Você deposita $1 de ouro no altar. $2 aceita sem uma palavra."),
                R(@"You renounce (.+)\. The silence afterwards is very large\.", "Você renuncia a $1. O silêncio depois é imenso."),
                R(@"You smash the altar of (.+)\. (.+) is delighted\.", "Você destroça o altar de $1. $2 se deleita."),
                R(@"You swear yourself to (.+), (.+)\. \((.+)\)", "Você jura lealdade a $1, $2. ($3)"),
                R(@"You turn your back on (.+)\. The old oath tears loose\.", "Você dá as costas a $1. O velho juramento se rompe."),
                R(@"(.+) curses you from beyond the stone\. \(-(\d+) HP\)", "$1 te amaldiçoa de além da pedra. (-$2 PV)"),
                R(@"(.+) does not answer\.", "$1 não responde."),
                R(@"(.+) favours you\. \((.+)\)", "$1 te favorece. ($2)"),
                R(@"(.+) frowns at (.+)\.", "$1 franze a testa para $2."),
                R(@"(.+) hears you\. Your wounds close\. \(-20 piety\)", "$1 te ouve. Suas feridas se fecham. (-20 de piedade)"),
                R(@"(.+) holds you dear\. \((.+)\)", "$1 te tem em alta conta. ($2)"),
                R(@"(.+) is displeased by your haste\. A cold hand shoves you down\. \(-(\d+) piety\)", "$1 se desagrada da sua pressa. Uma mão fria te empurra para baixo. (-$2 de piedade)"),
                R(@"(.+) is satisfied\. Your trial is done\. A gift: (.+)\.", "$1 está satisfeito. Sua provação acabou. Um presente: $2."),
                R(@"(.+) is silent\. \(a boon costs (\d+) piety; you have (\d+)\)", "$1 está em silêncio. (uma dádiva custa $2 de piedade; você tem $3)"),
                R(@"(.+) sets you a trial: (\d+) deeds the god likes \((.+)\)\. The reward is a gift: (.+)\.", "$1 te impõe uma provação: $2 feitos que o deus aprecia ($3). A recompensa é um presente: $4."),
                R(@"(.+)'s favour slips away\.", "O favor de $1 se esvai."),
                R(@"(.+) now holds you (revered|trusted|known|distrusted|hated)\.", "$1 agora tem você como $2."),
                // the rows of the altar menu (Game.Gods.cs): the god is a proper noun and rides the pattern as $1
                R(@"Swear to (.+) \((\d+) gold tribute\)", "Jurar a $1 (tributo de $2 de ouro)"),
                R(@"Swear to (.+)", "Jurar a $1"),
                R(@"Trial: (\d+)/(\d+) deeds (.+) likes", "Provação: $1/$2 feitos que $3 aprecia"),
                R(@"Ask (.+) for a trial", "Pedir uma provação a $1"),
                R(@"Renounce (.+) \(Enter again to confirm\)", "Renunciar a $1 (Enter de novo para confirmar)"),
                R(@"Renounce (.+)", "Renunciar a $1"),
                R(@"Forsake (.+), swear to (.+) \((\d+) gold\)", "Abandonar $1, jurar a $2 ($3 de ouro)"),
                // items
                R(@"A column of fire engulfs the (.+)!", "Uma coluna de fogo envolve {a1}!"),
                R(@"A (.+) appears in a puff of smoke!", "{u1} surge numa nuvem de fumaça!"),
                R(@"The (.+) glows briefly and seems fuller\.", "{a1} brilha por um instante e parece renovado."),
                R(@"The (.+) reels in confusion\.", "$1 cambaleia confuso."),
                R(@"Your (.+) crumbles to nothing!", "{a1} se desfaz em nada!"),
                R(@"Your (.+) glows with a soft blue light\.", "{a1} brilha com uma suave luz azul."),
                R(@"Your (.+) shudders, but can hold no more\.", "{a1} estremece, mas não aguenta mais."),
                R(@"(.+) flashes past and fades\.", "$1 passa como um relâmpago e some."),
                R(@"(.+) strikes the (.+) for (\d+) damage\.", "$1 atinge {a2} por $3 de dano."),
                // An imbued item fires its spell by itself (Game.Magic.cs): the weapon flares when you strike, a worn
                // piece stirs when you are struck. Two verbs, so two rows.
                R(@"Your (.+) flares: (.+)!", "{a1} faísca: $2!"),
                R(@"Your (.+) stirs: (.+)!", "{a1} desperta: $2!"),
                // spells
                R(@"The (.+) fades away\.", "$1 se desvanece."),
                R(@"The (.+) freezes to the spot\.", "$1 congela no lugar."),
                R(@"The (.+) has no mind to sway\.", "$1 não tem mente para influenciar."),
                R(@"The (.+) hits the (.+)\.", "$1 acerta {a2}."),
                R(@"The (.+) is destroyed\.", "$1 é destruído."),
                R(@"The (.+) is unaffected\.", "$1 não é afetado."),
                R(@"The (.+) is unharmed\.", "$1 sai ileso."),
                R(@"The (.+) is unmoved by death magic\.", "$1 não se abala com a magia da morte."),
                R(@"The (.+) knows no fear\.", "$1 não conhece o medo."),
                R(@"The (.+) resists your charm\.", "$1 resiste ao seu encanto."),
                R(@"The (.+) shakes off your charm\.", "$1 se livra do seu encanto."),
                R(@"The (.+) shrugs off the spell\.", "$1 ignora a magia."),
                R(@"The (.+) stands firm\.", "$1 se mantém firme."),
                R(@"The (.+) succumbs to the poison\.", "$1 sucumbe ao veneno."),
                R(@"The (.+) succumbs to its wounds\.", "$1 sucumbe aos ferimentos."),
                R(@"The (.+) burns to death\.", "$1 morre queimado."),
                R(@"The (.+) is cooked by the current\.", "{a1} é cozido pela corrente."),
                R(@"The (.+) falls in beside you\.", "$1 se junta a você."),
                R(@"The (.+) feels your hand!", "$1 sente sua mão!"),
                R(@"The (.+) is not a thing you can command\.", "$1 não é algo que você possa comandar."),
                R(@"The (.+) kneels to you, for now\.", "$1 se ajoelha diante de você, por ora."),
                R(@"The (.+) will have none of it\.", "$1 não quer saber disso."),
                R(@"The (.+) will not be moved\.", "$1 não vai se mover."),
                R(@"The (.+) will not kneel\.", "$1 não vai se ajoelhar."),
                R(@"The (.+) will not listen to you\.", "$1 não vai te ouvir."),
                R(@"(.+) blinks it away\.", "$1 pisca e se livra disso."),
                R(@"(.+) cannot be poisoned\.", "$1 não pode ser envenenado."),
                R(@"(.+) has no blood to spill\.", "$1 não tem sangue para derramar."),
                R(@"(.+) has no eyes to dazzle\.", "$1 não tem olhos para ofuscar."),
                R(@"(.+) has no mind to sway\.", "$1 não tem mente para influenciar."),
                R(@"(.+) is unaffected\.", "$1 não é afetado."),
                R(@"Your roar scatters (\d+) foe\(s\)!", "Seu rugido dispersa $1 inimigo(s)!"),
                R(@"(.+) knows no fear\.", "$1 não conhece o medo."),
                R(@"(.+) resists\.", "$1 resiste."),
                R(@"(.+) shakes off the spell\.", "$1 se livra da magia."),
                R(@"(.+) shrugs off the spell\.", "$1 ignora a magia."),
                R(@"(.+) stands firm\.", "$1 se mantém firme."),
                // The spell riders that strike a target without naming damage (Game.Rpg.cs): the target is the object.
                R(@"Frost bites (.+)\.", "O gelo morde {a1}."),
                R(@"Venom eats into (.+)\.", "O veneno corrói {a1}."),
                R(@"Sparks arc into (.+)\.", "Faíscas saltam em {a1}."),
                R(@"Radiance sears (.+)\.", "A radiância queima {a1}."),
                R(@"Dark power strikes (.+)\.", "O poder sombrio atinge {a1}."),
                R(@"Warmth knits your wounds \(\+(\d+) HP\)\.", "O calor fecha suas feridas (+$1 PV)."),
                R(@"Blood runs and the well fills\. \(-(\d+) HP, mana full\)", "O sangue escorre e o poço se enche. (-$1 PV, mana cheia)"),
                R(@"You and the (.+) trade places\.", "Você e {a1} trocam de lugar."),
                R(@"Your allies are mended too \((\d+)\)\.", "Seus aliados também são curados ($1)."),
                R(@"The words of (.+) writhe and slip away\. You feel dizzy\.", "As palavras de $1 se contorcem e escapam. Você sente tontura."),
                R(@"You learn (.+)!", "Você aprende $1!"),
                R(@"You need (\d+) mana for (.+) \(you have (\d+)\)\.", "Você precisa de $1 de mana para $2 (você tem $3)."),
                R(@"You skim (.+)\. Nothing in it you can use\.", "Você folheia {a1}. Nada nele que você possa usar."),
                R(@"Your (.+) fizzles\. \((\d+)% to fail\)", "Sua magia $1 falha. (chance de falha: $2%)"),
                R(@"(.+?) (the .+?) for (\d+), and it dies\.", "$1 {a2} por $3, e morre."),
                R(@"(.+?) (the .+?) for (\d+) damage\.", "$1 {a2} por $3 de dano."),
                // potions, rpg, surfaces, targeting
                R(@"Acid burns your throat for (\d+) damage!", "O ácido queima sua garganta: $1 de dano!"),
                R(@"It carries the spell (.+): you can cast it while you hold it", "Carrega a magia $1: você pode conjurá-la enquanto a segura"),
                R(@"It is (.+)!", "É $1!"),
                R(@"You advance to level (\d+) \((.+)\)! Choose from (\d+) advancement\(s\) \(Shift\+C\)\.", "Você avança ao nível $1 ($2)! Escolha entre $3 evolução(ões) (Shift+C)."),
                R(@"You grow (.+)\. (.+)\.", "Você ganha $1. $2."),
                R(@"(.+) is not available to you now\.", "$1 não está disponível para você agora."),
                R(@"The current shocks you for (\d+)!", "A corrente te eletriza: $1!"),
                R(@"The (.+) catches fire!", "$1 pega fogo!"),
                R(@"You burn! \(-(\d+)\)", "Você queima! (-$1)"),
                R(@"\((\d+),(\d+)\) (.+), with:", "($1,$2) $3, com:"),
                R(@"The (.+) has nothing worth taking\.", "$1 não tem nada que valha levar."),
                R(@"The (.+) is carrying:", "$1 carrega:"),
                // "rubble" is plural in Portuguese ("os escombros"): it takes its own line, the rest take an article
                R(@"You dig through the rubble \(effort (\d+)\)\.", "Você cava através dos escombros (esforço $1)."),
                R(@"You dig through the (.+) \(effort (\d+)\)\.", "Você cava através de {a1} (esforço $2)."),
                R(@"You need (\d+) experience to train (.+); you have (\d+)\.", "Você precisa de $1 de experiência para treinar $2; você tem $3."),
                R(@"You train (.+): (\d+) -> (\d+)\.", "Você treina $1: $2 -> $3."),
                R(@"The (.+) bursts into flame!", "$1 explode em chamas!"),
                R(@"The (.+) squeals, and another scurries out of the dark\.", "$1 guincha, e outro sai correndo do escuro."),
                R(@"The (.+)'s bite festers\.", "A mordida {d1} infecciona."),
                R(@"The (.+)'s blow rings through your skull\.", "O golpe {d1} ressoa no seu crânio."),
                // game
                R(@"A dart hits you for (\d+) damage\.", "Um dardo atinge você: $1 de dano."),
                R(@"A spike trap pierces your foot for (\d+) damage!", "Uma armadilha de espetos perfura seu pé: $1 de dano!"),
                R(@"The (.+) explodes for (\d+) damage!", "$1 explode: $2 de dano!"),
                R(@"The (.+) smashes through the rubble\.", "$1 abre caminho pelos escombros."),
                R(@"The poison burns for (\d+) damage\.", "O veneno queima: $1 de dano."),
                R(@"You collapse for (\d+) damage\.", "Você desaba: $1 de dano."),
                R(@"Your (.+) fades\.", "{a1} que você invocou se desfaz."),
                R(@"You are in (.+)", "Você está em $1"),
                // screens
                R(@"HP/level (\d+)   Gold (\d+)", "PV/nível $1   Ouro $2"),
                R(@"Attributes (.+)", "Atributos $1"),
                R(@"Kit: (.+)", "Kit: $1"),
                R(@"Skills: none", "Perícias: nenhuma"),
                R(@"Skills: (.+)", "Perícias: $1"),
                R(@"Cursor (\d+),(\d+)", "Cursor $1,$2"),
                R(@"Str:\s*(\d+)/(\d*)\s+Dex:\s*(\d+)\s+Con:\s*(\d+)\s+Int:\s*(\d+)\s+Wis:\s*(\d+)\s+Cha:\s*(\d+)", "For:$1/$2 Des:$3 Con:$4 Int:$5 Sab:$6 Car:$7"),
                R(@"It is (.+)! \((.+)\)", "É $1! ($2)"),
                R(@"([+-]\d+) (to hit|damage|evasion|spell power|spell focus|stealth)", "$1 $2"),
                R(@"([+-]\d+) AC", "$1 CA"),
                R(@"(\d+)% life steal", "$1% de roubo de vida"),
                R(@"([+-]\d)d(\d+) (\w+)", "$1d$2 $3"),
                R(@"(fire|cold|lightning|poison|necrotic|holy) (-?\d+)%", "$1 $2%"),
                R(@"(Human|Dwarf|Elf|Halfling|Orc|Gnome|Ashen) (.+)", "$2 $1"),
            };
            Rx.InsertRange(0, front);
            // Left last on purpose: " : level N" only decorates a level name, so the patterns that translate a whole
            // one ("You arrive at The Dungeons : level 1." -> "Você chega às Masmorras, nível 1.") must see it first.
            Rx.Add(R(@"(.+) : level (\d+)", "$1, nível $2"));
        }
    }
}
